// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: invoke.proto

package invoke

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	context "github.com/Overclock-Validator/mithril/pkg/protosol-go/context"
	metadata "github.com/Overclock-Validator/mithril/pkg/protosol-go/metadata"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InstrAcct struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Selects an account in an external list
	Index         uint32 `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	IsWritable    bool   `protobuf:"varint,2,opt,name=is_writable,json=isWritable,proto3" json:"is_writable,omitempty"`
	IsSigner      bool   `protobuf:"varint,3,opt,name=is_signer,json=isSigner,proto3" json:"is_signer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstrAcct) Reset() {
	*x = InstrAcct{}
	mi := &file_invoke_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstrAcct) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstrAcct) ProtoMessage() {}

func (x *InstrAcct) ProtoReflect() protoreflect.Message {
	mi := &file_invoke_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstrAcct.ProtoReflect.Descriptor instead.
func (*InstrAcct) Descriptor() ([]byte, []int) {
	return file_invoke_proto_rawDescGZIP(), []int{0}
}

func (x *InstrAcct) GetIndex() uint32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *InstrAcct) GetIsWritable() bool {
	if x != nil {
		return x.IsWritable
	}
	return false
}

func (x *InstrAcct) GetIsSigner() bool {
	if x != nil {
		return x.IsSigner
	}
	return false
}

// The execution context of a program invocation (aka instruction).
// Contains all required information to independently replay an instruction.
// Also includes partial transaction context.
type InstrContext struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The address of the program invoked.  (32 bytes)
	ProgramId []byte `protobuf:"bytes,1,opt,name=program_id,json=programId,proto3" json:"program_id,omitempty"`
	// Account state accessed by the instruction.  This may include
	// indirect accesses like sysvars.
	Accounts []*context.AcctState `protobuf:"bytes,3,rep,name=accounts,proto3" json:"accounts,omitempty"`
	// Account access list for this instruction (refers to above accounts list)
	InstrAccounts []*InstrAcct `protobuf:"bytes,4,rep,name=instr_accounts,json=instrAccounts,proto3" json:"instr_accounts,omitempty"`
	// The input data passed to program execution.
	Data          []byte                `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`
	CuAvail       uint64                `protobuf:"varint,6,opt,name=cu_avail,json=cuAvail,proto3" json:"cu_avail,omitempty"`
	SlotContext   *context.SlotContext  `protobuf:"bytes,8,opt,name=slot_context,json=slotContext,proto3" json:"slot_context,omitempty"`
	EpochContext  *context.EpochContext `protobuf:"bytes,9,opt,name=epoch_context,json=epochContext,proto3" json:"epoch_context,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstrContext) Reset() {
	*x = InstrContext{}
	mi := &file_invoke_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstrContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstrContext) ProtoMessage() {}

func (x *InstrContext) ProtoReflect() protoreflect.Message {
	mi := &file_invoke_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstrContext.ProtoReflect.Descriptor instead.
func (*InstrContext) Descriptor() ([]byte, []int) {
	return file_invoke_proto_rawDescGZIP(), []int{1}
}

func (x *InstrContext) GetProgramId() []byte {
	if x != nil {
		return x.ProgramId
	}
	return nil
}

func (x *InstrContext) GetAccounts() []*context.AcctState {
	if x != nil {
		return x.Accounts
	}
	return nil
}

func (x *InstrContext) GetInstrAccounts() []*InstrAcct {
	if x != nil {
		return x.InstrAccounts
	}
	return nil
}

func (x *InstrContext) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *InstrContext) GetCuAvail() uint64 {
	if x != nil {
		return x.CuAvail
	}
	return 0
}

func (x *InstrContext) GetSlotContext() *context.SlotContext {
	if x != nil {
		return x.SlotContext
	}
	return nil
}

func (x *InstrContext) GetEpochContext() *context.EpochContext {
	if x != nil {
		return x.EpochContext
	}
	return nil
}

// The results of executing an InstrContext.
type InstrEffects struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// result is zero if the instruction executed succesfully.
	// Otherwise, a non-zero error code.  Error codes are not relevant to
	// consensus.
	Result int32 `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	// Some error cases additionally have a custom error code.  Unlike
	// the expected_result, this is stable across clients.
	CustomErr uint32 `protobuf:"varint,2,opt,name=custom_err,json=customErr,proto3" json:"custom_err,omitempty"`
	// Copies of accounts that were changed.  May be in an arbitrary
	// order.  The pubkey of each account is unique in this list.  Each
	// account address modified here must also be in the
	// InstrContext.
	ModifiedAccounts []*context.AcctState `protobuf:"bytes,3,rep,name=modified_accounts,json=modifiedAccounts,proto3" json:"modified_accounts,omitempty"`
	CuAvail          uint64               `protobuf:"varint,4,opt,name=cu_avail,json=cuAvail,proto3" json:"cu_avail,omitempty"`
	// Instruction return data.
	ReturnData    []byte `protobuf:"bytes,5,opt,name=return_data,json=returnData,proto3" json:"return_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstrEffects) Reset() {
	*x = InstrEffects{}
	mi := &file_invoke_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstrEffects) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstrEffects) ProtoMessage() {}

func (x *InstrEffects) ProtoReflect() protoreflect.Message {
	mi := &file_invoke_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstrEffects.ProtoReflect.Descriptor instead.
func (*InstrEffects) Descriptor() ([]byte, []int) {
	return file_invoke_proto_rawDescGZIP(), []int{2}
}

func (x *InstrEffects) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

func (x *InstrEffects) GetCustomErr() uint32 {
	if x != nil {
		return x.CustomErr
	}
	return 0
}

func (x *InstrEffects) GetModifiedAccounts() []*context.AcctState {
	if x != nil {
		return x.ModifiedAccounts
	}
	return nil
}

func (x *InstrEffects) GetCuAvail() uint64 {
	if x != nil {
		return x.CuAvail
	}
	return 0
}

func (x *InstrEffects) GetReturnData() []byte {
	if x != nil {
		return x.ReturnData
	}
	return nil
}

// An instruction processing test fixture.
type InstrFixture struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Metadata      *metadata.FixtureMetadata `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Input         *InstrContext             `protobuf:"bytes,2,opt,name=input,proto3" json:"input,omitempty"`
	Output        *InstrEffects             `protobuf:"bytes,3,opt,name=output,proto3" json:"output,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstrFixture) Reset() {
	*x = InstrFixture{}
	mi := &file_invoke_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstrFixture) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstrFixture) ProtoMessage() {}

func (x *InstrFixture) ProtoReflect() protoreflect.Message {
	mi := &file_invoke_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstrFixture.ProtoReflect.Descriptor instead.
func (*InstrFixture) Descriptor() ([]byte, []int) {
	return file_invoke_proto_rawDescGZIP(), []int{3}
}

func (x *InstrFixture) GetMetadata() *metadata.FixtureMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *InstrFixture) GetInput() *InstrContext {
	if x != nil {
		return x.Input
	}
	return nil
}

func (x *InstrFixture) GetOutput() *InstrEffects {
	if x != nil {
		return x.Output
	}
	return nil
}

var File_invoke_proto protoreflect.FileDescriptor

const file_invoke_proto_rawDesc = "" +
	"\n" +
	"\finvoke.proto\x12\x16org.solana.sealevel.v1\x1a\rcontext.proto\x1a\x0emetadata.proto\"_\n" +
	"\tInstrAcct\x12\x14\n" +
	"\x05index\x18\x01 \x01(\rR\x05index\x12\x1f\n" +
	"\vis_writable\x18\x02 \x01(\bR\n" +
	"isWritable\x12\x1b\n" +
	"\tis_signer\x18\x03 \x01(\bR\bisSigner\"\xf8\x02\n" +
	"\fInstrContext\x12\x1d\n" +
	"\n" +
	"program_id\x18\x01 \x01(\fR\tprogramId\x12=\n" +
	"\baccounts\x18\x03 \x03(\v2!.org.solana.sealevel.v1.AcctStateR\baccounts\x12H\n" +
	"\x0einstr_accounts\x18\x04 \x03(\v2!.org.solana.sealevel.v1.InstrAcctR\rinstrAccounts\x12\x12\n" +
	"\x04data\x18\x05 \x01(\fR\x04data\x12\x19\n" +
	"\bcu_avail\x18\x06 \x01(\x04R\acuAvail\x12F\n" +
	"\fslot_context\x18\b \x01(\v2#.org.solana.sealevel.v1.SlotContextR\vslotContext\x12I\n" +
	"\repoch_context\x18\t \x01(\v2$.org.solana.sealevel.v1.EpochContextR\fepochContext\"\xd1\x01\n" +
	"\fInstrEffects\x12\x16\n" +
	"\x06result\x18\x01 \x01(\x05R\x06result\x12\x1d\n" +
	"\n" +
	"custom_err\x18\x02 \x01(\rR\tcustomErr\x12N\n" +
	"\x11modified_accounts\x18\x03 \x03(\v2!.org.solana.sealevel.v1.AcctStateR\x10modifiedAccounts\x12\x19\n" +
	"\bcu_avail\x18\x04 \x01(\x04R\acuAvail\x12\x1f\n" +
	"\vreturn_data\x18\x05 \x01(\fR\n" +
	"returnData\"\xcd\x01\n" +
	"\fInstrFixture\x12C\n" +
	"\bmetadata\x18\x01 \x01(\v2'.org.solana.sealevel.v1.FixtureMetadataR\bmetadata\x12:\n" +
	"\x05input\x18\x02 \x01(\v2$.org.solana.sealevel.v1.InstrContextR\x05input\x12<\n" +
	"\x06output\x18\x03 \x01(\v2$.org.solana.sealevel.v1.InstrEffectsR\x06outputb\x06proto3"

var (
	file_invoke_proto_rawDescOnce sync.Once
	file_invoke_proto_rawDescData []byte
)

func file_invoke_proto_rawDescGZIP() []byte {
	file_invoke_proto_rawDescOnce.Do(func() {
		file_invoke_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_invoke_proto_rawDesc), len(file_invoke_proto_rawDesc)))
	})
	return file_invoke_proto_rawDescData
}

var file_invoke_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_invoke_proto_goTypes = []any{
	(*InstrAcct)(nil),                // 0: org.solana.sealevel.v1.InstrAcct
	(*InstrContext)(nil),             // 1: org.solana.sealevel.v1.InstrContext
	(*InstrEffects)(nil),             // 2: org.solana.sealevel.v1.InstrEffects
	(*InstrFixture)(nil),             // 3: org.solana.sealevel.v1.InstrFixture
	(*context.AcctState)(nil),        // 4: org.solana.sealevel.v1.AcctState
	(*context.SlotContext)(nil),      // 5: org.solana.sealevel.v1.SlotContext
	(*context.EpochContext)(nil),     // 6: org.solana.sealevel.v1.EpochContext
	(*metadata.FixtureMetadata)(nil), // 7: org.solana.sealevel.v1.FixtureMetadata
}
var file_invoke_proto_depIdxs = []int32{
	4, // 0: org.solana.sealevel.v1.InstrContext.accounts:type_name -> org.solana.sealevel.v1.AcctState
	0, // 1: org.solana.sealevel.v1.InstrContext.instr_accounts:type_name -> org.solana.sealevel.v1.InstrAcct
	5, // 2: org.solana.sealevel.v1.InstrContext.slot_context:type_name -> org.solana.sealevel.v1.SlotContext
	6, // 3: org.solana.sealevel.v1.InstrContext.epoch_context:type_name -> org.solana.sealevel.v1.EpochContext
	4, // 4: org.solana.sealevel.v1.InstrEffects.modified_accounts:type_name -> org.solana.sealevel.v1.AcctState
	7, // 5: org.solana.sealevel.v1.InstrFixture.metadata:type_name -> org.solana.sealevel.v1.FixtureMetadata
	1, // 6: org.solana.sealevel.v1.InstrFixture.input:type_name -> org.solana.sealevel.v1.InstrContext
	2, // 7: org.solana.sealevel.v1.InstrFixture.output:type_name -> org.solana.sealevel.v1.InstrEffects
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_invoke_proto_init() }
func file_invoke_proto_init() {
	if File_invoke_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_invoke_proto_rawDesc), len(file_invoke_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_invoke_proto_goTypes,
		DependencyIndexes: file_invoke_proto_depIdxs,
		MessageInfos:      file_invoke_proto_msgTypes,
	}.Build()
	File_invoke_proto = out.File
	file_invoke_proto_goTypes = nil
	file_invoke_proto_depIdxs = nil
}
