// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: shred.proto

package shred

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// raw bytes to test shred parsing
type ShredBinary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShredBinary) Reset() {
	*x = ShredBinary{}
	mi := &file_shred_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShredBinary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShredBinary) ProtoMessage() {}

func (x *ShredBinary) ProtoReflect() protoreflect.Message {
	mi := &file_shred_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShredBinary.ProtoReflect.Descriptor instead.
func (*ShredBinary) Descriptor() ([]byte, []int) {
	return file_shred_proto_rawDescGZIP(), []int{0}
}

func (x *ShredBinary) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type DataHeader struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ParentOff     uint32                 `protobuf:"varint,1,opt,name=parent_off,json=parentOff,proto3" json:"parent_off,omitempty"`
	Flags         uint32                 `protobuf:"varint,2,opt,name=flags,proto3" json:"flags,omitempty"`
	Size          uint32                 `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataHeader) Reset() {
	*x = DataHeader{}
	mi := &file_shred_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataHeader) ProtoMessage() {}

func (x *DataHeader) ProtoReflect() protoreflect.Message {
	mi := &file_shred_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataHeader.ProtoReflect.Descriptor instead.
func (*DataHeader) Descriptor() ([]byte, []int) {
	return file_shred_proto_rawDescGZIP(), []int{1}
}

func (x *DataHeader) GetParentOff() uint32 {
	if x != nil {
		return x.ParentOff
	}
	return 0
}

func (x *DataHeader) GetFlags() uint32 {
	if x != nil {
		return x.Flags
	}
	return 0
}

func (x *DataHeader) GetSize() uint32 {
	if x != nil {
		return x.Size
	}
	return 0
}

type CodeHeader struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DataCnt       uint32                 `protobuf:"varint,1,opt,name=data_cnt,json=dataCnt,proto3" json:"data_cnt,omitempty"`
	CodeCnt       uint32                 `protobuf:"varint,2,opt,name=code_cnt,json=codeCnt,proto3" json:"code_cnt,omitempty"`
	Idx           uint32                 `protobuf:"varint,3,opt,name=idx,proto3" json:"idx,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CodeHeader) Reset() {
	*x = CodeHeader{}
	mi := &file_shred_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CodeHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CodeHeader) ProtoMessage() {}

func (x *CodeHeader) ProtoReflect() protoreflect.Message {
	mi := &file_shred_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CodeHeader.ProtoReflect.Descriptor instead.
func (*CodeHeader) Descriptor() ([]byte, []int) {
	return file_shred_proto_rawDescGZIP(), []int{2}
}

func (x *CodeHeader) GetDataCnt() uint32 {
	if x != nil {
		return x.DataCnt
	}
	return 0
}

func (x *CodeHeader) GetCodeCnt() uint32 {
	if x != nil {
		return x.CodeCnt
	}
	return 0
}

func (x *CodeHeader) GetIdx() uint32 {
	if x != nil {
		return x.Idx
	}
	return 0
}

type ParsedShred struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Signature string                 `protobuf:"bytes,1,opt,name=signature,proto3" json:"signature,omitempty"`
	Variant   uint32                 `protobuf:"varint,2,opt,name=variant,proto3" json:"variant,omitempty"`
	Slot      uint64                 `protobuf:"varint,3,opt,name=slot,proto3" json:"slot,omitempty"`
	Idx       uint32                 `protobuf:"varint,4,opt,name=idx,proto3" json:"idx,omitempty"`
	Version   uint32                 `protobuf:"varint,5,opt,name=version,proto3" json:"version,omitempty"`
	FecSetIdx uint32                 `protobuf:"varint,6,opt,name=fec_set_idx,json=fecSetIdx,proto3" json:"fec_set_idx,omitempty"`
	// Types that are valid to be assigned to ShredType:
	//
	//	*ParsedShred_Data
	//	*ParsedShred_Code
	ShredType     isParsedShred_ShredType `protobuf_oneof:"shred_type"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParsedShred) Reset() {
	*x = ParsedShred{}
	mi := &file_shred_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParsedShred) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParsedShred) ProtoMessage() {}

func (x *ParsedShred) ProtoReflect() protoreflect.Message {
	mi := &file_shred_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParsedShred.ProtoReflect.Descriptor instead.
func (*ParsedShred) Descriptor() ([]byte, []int) {
	return file_shred_proto_rawDescGZIP(), []int{3}
}

func (x *ParsedShred) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *ParsedShred) GetVariant() uint32 {
	if x != nil {
		return x.Variant
	}
	return 0
}

func (x *ParsedShred) GetSlot() uint64 {
	if x != nil {
		return x.Slot
	}
	return 0
}

func (x *ParsedShred) GetIdx() uint32 {
	if x != nil {
		return x.Idx
	}
	return 0
}

func (x *ParsedShred) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *ParsedShred) GetFecSetIdx() uint32 {
	if x != nil {
		return x.FecSetIdx
	}
	return 0
}

func (x *ParsedShred) GetShredType() isParsedShred_ShredType {
	if x != nil {
		return x.ShredType
	}
	return nil
}

func (x *ParsedShred) GetData() *DataHeader {
	if x != nil {
		if x, ok := x.ShredType.(*ParsedShred_Data); ok {
			return x.Data
		}
	}
	return nil
}

func (x *ParsedShred) GetCode() *CodeHeader {
	if x != nil {
		if x, ok := x.ShredType.(*ParsedShred_Code); ok {
			return x.Code
		}
	}
	return nil
}

type isParsedShred_ShredType interface {
	isParsedShred_ShredType()
}

type ParsedShred_Data struct {
	Data *DataHeader `protobuf:"bytes,7,opt,name=data,proto3,oneof"`
}

type ParsedShred_Code struct {
	Code *CodeHeader `protobuf:"bytes,8,opt,name=code,proto3,oneof"`
}

func (*ParsedShred_Data) isParsedShred_ShredType() {}

func (*ParsedShred_Code) isParsedShred_ShredType() {}

// If shred is accepted after parseing. This is all we are interested in
// between Firedancer and Agave.
type AcceptsShred struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Valid         bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcceptsShred) Reset() {
	*x = AcceptsShred{}
	mi := &file_shred_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptsShred) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptsShred) ProtoMessage() {}

func (x *AcceptsShred) ProtoReflect() protoreflect.Message {
	mi := &file_shred_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptsShred.ProtoReflect.Descriptor instead.
func (*AcceptsShred) Descriptor() ([]byte, []int) {
	return file_shred_proto_rawDescGZIP(), []int{4}
}

func (x *AcceptsShred) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

var File_shred_proto protoreflect.FileDescriptor

const file_shred_proto_rawDesc = "" +
	"\n" +
	"\vshred.proto\x12\x16org.solana.sealevel.v1\"!\n" +
	"\vShredBinary\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"U\n" +
	"\n" +
	"DataHeader\x12\x1d\n" +
	"\n" +
	"parent_off\x18\x01 \x01(\rR\tparentOff\x12\x14\n" +
	"\x05flags\x18\x02 \x01(\rR\x05flags\x12\x12\n" +
	"\x04size\x18\x03 \x01(\rR\x04size\"T\n" +
	"\n" +
	"CodeHeader\x12\x19\n" +
	"\bdata_cnt\x18\x01 \x01(\rR\adataCnt\x12\x19\n" +
	"\bcode_cnt\x18\x02 \x01(\rR\acodeCnt\x12\x10\n" +
	"\x03idx\x18\x03 \x01(\rR\x03idx\"\xa7\x02\n" +
	"\vParsedShred\x12\x1c\n" +
	"\tsignature\x18\x01 \x01(\tR\tsignature\x12\x18\n" +
	"\avariant\x18\x02 \x01(\rR\avariant\x12\x12\n" +
	"\x04slot\x18\x03 \x01(\x04R\x04slot\x12\x10\n" +
	"\x03idx\x18\x04 \x01(\rR\x03idx\x12\x18\n" +
	"\aversion\x18\x05 \x01(\rR\aversion\x12\x1e\n" +
	"\vfec_set_idx\x18\x06 \x01(\rR\tfecSetIdx\x128\n" +
	"\x04data\x18\a \x01(\v2\".org.solana.sealevel.v1.DataHeaderH\x00R\x04data\x128\n" +
	"\x04code\x18\b \x01(\v2\".org.solana.sealevel.v1.CodeHeaderH\x00R\x04codeB\f\n" +
	"\n" +
	"shred_type\"$\n" +
	"\fAcceptsShred\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05validb\x06proto3"

var (
	file_shred_proto_rawDescOnce sync.Once
	file_shred_proto_rawDescData []byte
)

func file_shred_proto_rawDescGZIP() []byte {
	file_shred_proto_rawDescOnce.Do(func() {
		file_shred_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_shred_proto_rawDesc), len(file_shred_proto_rawDesc)))
	})
	return file_shred_proto_rawDescData
}

var file_shred_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_shred_proto_goTypes = []any{
	(*ShredBinary)(nil),  // 0: org.solana.sealevel.v1.ShredBinary
	(*DataHeader)(nil),   // 1: org.solana.sealevel.v1.DataHeader
	(*CodeHeader)(nil),   // 2: org.solana.sealevel.v1.CodeHeader
	(*ParsedShred)(nil),  // 3: org.solana.sealevel.v1.ParsedShred
	(*AcceptsShred)(nil), // 4: org.solana.sealevel.v1.AcceptsShred
}
var file_shred_proto_depIdxs = []int32{
	1, // 0: org.solana.sealevel.v1.ParsedShred.data:type_name -> org.solana.sealevel.v1.DataHeader
	2, // 1: org.solana.sealevel.v1.ParsedShred.code:type_name -> org.solana.sealevel.v1.CodeHeader
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_shred_proto_init() }
func file_shred_proto_init() {
	if File_shred_proto != nil {
		return
	}
	file_shred_proto_msgTypes[3].OneofWrappers = []any{
		(*ParsedShred_Data)(nil),
		(*ParsedShred_Code)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shred_proto_rawDesc), len(file_shred_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_shred_proto_goTypes,
		DependencyIndexes: file_shred_proto_depIdxs,
		MessageInfos:      file_shred_proto_msgTypes,
	}.Build()
	File_shred_proto = out.File
	file_shred_proto_goTypes = nil
	file_shred_proto_depIdxs = nil
}
