// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: elf.proto

package elf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	context "github.com/Overclock-Validator/mithril/pkg/protosol-go/context"
	metadata "github.com/Overclock-Validator/mithril/pkg/protosol-go/metadata"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ELFBinary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ELFBinary) Reset() {
	*x = ELFBinary{}
	mi := &file_elf_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ELFBinary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ELFBinary) ProtoMessage() {}

func (x *ELFBinary) ProtoReflect() protoreflect.Message {
	mi := &file_elf_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ELFBinary.ProtoReflect.Descriptor instead.
func (*ELFBinary) Descriptor() ([]byte, []int) {
	return file_elf_proto_rawDescGZIP(), []int{0}
}

func (x *ELFBinary) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// Wrapper for the ELF binary and the features that the loader should use
// Note that we currently hardcode the features to be used by the loader,
// so features isn't actually used yet.
type ELFLoaderCtx struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Elf           *ELFBinary             `protobuf:"bytes,1,opt,name=elf,proto3" json:"elf,omitempty"`
	Features      *context.FeatureSet    `protobuf:"bytes,2,opt,name=features,proto3" json:"features,omitempty"`
	DeployChecks  bool                   `protobuf:"varint,4,opt,name=deploy_checks,json=deployChecks,proto3" json:"deploy_checks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ELFLoaderCtx) Reset() {
	*x = ELFLoaderCtx{}
	mi := &file_elf_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ELFLoaderCtx) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ELFLoaderCtx) ProtoMessage() {}

func (x *ELFLoaderCtx) ProtoReflect() protoreflect.Message {
	mi := &file_elf_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ELFLoaderCtx.ProtoReflect.Descriptor instead.
func (*ELFLoaderCtx) Descriptor() ([]byte, []int) {
	return file_elf_proto_rawDescGZIP(), []int{1}
}

func (x *ELFLoaderCtx) GetElf() *ELFBinary {
	if x != nil {
		return x.Elf
	}
	return nil
}

func (x *ELFLoaderCtx) GetFeatures() *context.FeatureSet {
	if x != nil {
		return x.Features
	}
	return nil
}

func (x *ELFLoaderCtx) GetDeployChecks() bool {
	if x != nil {
		return x.DeployChecks
	}
	return false
}

// Captures the results of a elf binary load.
// Structurally similar to fd_sbpf_program_t
type ELFLoaderEffects struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Rodata   []byte                 `protobuf:"bytes,1,opt,name=rodata,proto3" json:"rodata,omitempty"`
	RodataSz uint64                 `protobuf:"varint,2,opt,name=rodata_sz,json=rodataSz,proto3" json:"rodata_sz,omitempty"`
	// bytes text = 3; // not needed, just points to a region in rodata
	TextCnt       uint64   `protobuf:"varint,4,opt,name=text_cnt,json=textCnt,proto3" json:"text_cnt,omitempty"`
	TextOff       uint64   `protobuf:"varint,5,opt,name=text_off,json=textOff,proto3" json:"text_off,omitempty"`
	EntryPc       uint64   `protobuf:"varint,6,opt,name=entry_pc,json=entryPc,proto3" json:"entry_pc,omitempty"`
	Calldests     []uint64 `protobuf:"varint,7,rep,packed,name=calldests,proto3" json:"calldests,omitempty"`
	Error         int32    `protobuf:"varint,8,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ELFLoaderEffects) Reset() {
	*x = ELFLoaderEffects{}
	mi := &file_elf_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ELFLoaderEffects) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ELFLoaderEffects) ProtoMessage() {}

func (x *ELFLoaderEffects) ProtoReflect() protoreflect.Message {
	mi := &file_elf_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ELFLoaderEffects.ProtoReflect.Descriptor instead.
func (*ELFLoaderEffects) Descriptor() ([]byte, []int) {
	return file_elf_proto_rawDescGZIP(), []int{2}
}

func (x *ELFLoaderEffects) GetRodata() []byte {
	if x != nil {
		return x.Rodata
	}
	return nil
}

func (x *ELFLoaderEffects) GetRodataSz() uint64 {
	if x != nil {
		return x.RodataSz
	}
	return 0
}

func (x *ELFLoaderEffects) GetTextCnt() uint64 {
	if x != nil {
		return x.TextCnt
	}
	return 0
}

func (x *ELFLoaderEffects) GetTextOff() uint64 {
	if x != nil {
		return x.TextOff
	}
	return 0
}

func (x *ELFLoaderEffects) GetEntryPc() uint64 {
	if x != nil {
		return x.EntryPc
	}
	return 0
}

func (x *ELFLoaderEffects) GetCalldests() []uint64 {
	if x != nil {
		return x.Calldests
	}
	return nil
}

func (x *ELFLoaderEffects) GetError() int32 {
	if x != nil {
		return x.Error
	}
	return 0
}

type ELFLoaderFixture struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Metadata      *metadata.FixtureMetadata `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Input         *ELFLoaderCtx             `protobuf:"bytes,2,opt,name=input,proto3" json:"input,omitempty"`
	Output        *ELFLoaderEffects         `protobuf:"bytes,3,opt,name=output,proto3" json:"output,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ELFLoaderFixture) Reset() {
	*x = ELFLoaderFixture{}
	mi := &file_elf_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ELFLoaderFixture) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ELFLoaderFixture) ProtoMessage() {}

func (x *ELFLoaderFixture) ProtoReflect() protoreflect.Message {
	mi := &file_elf_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ELFLoaderFixture.ProtoReflect.Descriptor instead.
func (*ELFLoaderFixture) Descriptor() ([]byte, []int) {
	return file_elf_proto_rawDescGZIP(), []int{3}
}

func (x *ELFLoaderFixture) GetMetadata() *metadata.FixtureMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *ELFLoaderFixture) GetInput() *ELFLoaderCtx {
	if x != nil {
		return x.Input
	}
	return nil
}

func (x *ELFLoaderFixture) GetOutput() *ELFLoaderEffects {
	if x != nil {
		return x.Output
	}
	return nil
}

var File_elf_proto protoreflect.FileDescriptor

const file_elf_proto_rawDesc = "" +
	"\n" +
	"\telf.proto\x12\x16org.solana.sealevel.v1\x1a\rcontext.proto\x1a\x0emetadata.proto\"\x1f\n" +
	"\tELFBinary\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"\xa8\x01\n" +
	"\fELFLoaderCtx\x123\n" +
	"\x03elf\x18\x01 \x01(\v2!.org.solana.sealevel.v1.ELFBinaryR\x03elf\x12>\n" +
	"\bfeatures\x18\x02 \x01(\v2\".org.solana.sealevel.v1.FeatureSetR\bfeatures\x12#\n" +
	"\rdeploy_checks\x18\x04 \x01(\bR\fdeployChecks\"\xcc\x01\n" +
	"\x10ELFLoaderEffects\x12\x16\n" +
	"\x06rodata\x18\x01 \x01(\fR\x06rodata\x12\x1b\n" +
	"\trodata_sz\x18\x02 \x01(\x04R\brodataSz\x12\x19\n" +
	"\btext_cnt\x18\x04 \x01(\x04R\atextCnt\x12\x19\n" +
	"\btext_off\x18\x05 \x01(\x04R\atextOff\x12\x19\n" +
	"\bentry_pc\x18\x06 \x01(\x04R\aentryPc\x12\x1c\n" +
	"\tcalldests\x18\a \x03(\x04R\tcalldests\x12\x14\n" +
	"\x05error\x18\b \x01(\x05R\x05error\"\xd5\x01\n" +
	"\x10ELFLoaderFixture\x12C\n" +
	"\bmetadata\x18\x01 \x01(\v2'.org.solana.sealevel.v1.FixtureMetadataR\bmetadata\x12:\n" +
	"\x05input\x18\x02 \x01(\v2$.org.solana.sealevel.v1.ELFLoaderCtxR\x05input\x12@\n" +
	"\x06output\x18\x03 \x01(\v2(.org.solana.sealevel.v1.ELFLoaderEffectsR\x06outputb\x06proto3"

var (
	file_elf_proto_rawDescOnce sync.Once
	file_elf_proto_rawDescData []byte
)

func file_elf_proto_rawDescGZIP() []byte {
	file_elf_proto_rawDescOnce.Do(func() {
		file_elf_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_elf_proto_rawDesc), len(file_elf_proto_rawDesc)))
	})
	return file_elf_proto_rawDescData
}

var file_elf_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_elf_proto_goTypes = []any{
	(*ELFBinary)(nil),                // 0: org.solana.sealevel.v1.ELFBinary
	(*ELFLoaderCtx)(nil),             // 1: org.solana.sealevel.v1.ELFLoaderCtx
	(*ELFLoaderEffects)(nil),         // 2: org.solana.sealevel.v1.ELFLoaderEffects
	(*ELFLoaderFixture)(nil),         // 3: org.solana.sealevel.v1.ELFLoaderFixture
	(*context.FeatureSet)(nil),       // 4: org.solana.sealevel.v1.FeatureSet
	(*metadata.FixtureMetadata)(nil), // 5: org.solana.sealevel.v1.FixtureMetadata
}
var file_elf_proto_depIdxs = []int32{
	0, // 0: org.solana.sealevel.v1.ELFLoaderCtx.elf:type_name -> org.solana.sealevel.v1.ELFBinary
	4, // 1: org.solana.sealevel.v1.ELFLoaderCtx.features:type_name -> org.solana.sealevel.v1.FeatureSet
	5, // 2: org.solana.sealevel.v1.ELFLoaderFixture.metadata:type_name -> org.solana.sealevel.v1.FixtureMetadata
	1, // 3: org.solana.sealevel.v1.ELFLoaderFixture.input:type_name -> org.solana.sealevel.v1.ELFLoaderCtx
	2, // 4: org.solana.sealevel.v1.ELFLoaderFixture.output:type_name -> org.solana.sealevel.v1.ELFLoaderEffects
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_elf_proto_init() }
func file_elf_proto_init() {
	if File_elf_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_elf_proto_rawDesc), len(file_elf_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_elf_proto_goTypes,
		DependencyIndexes: file_elf_proto_depIdxs,
		MessageInfos:      file_elf_proto_msgTypes,
	}.Build()
	File_elf_proto = out.File
	file_elf_proto_goTypes = nil
	file_elf_proto_depIdxs = nil
}
