// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: txn.proto

package txn

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	context "github.com/Overclock-Validator/mithril/pkg/protosol-go/context"
	metadata "github.com/Overclock-Validator/mithril/pkg/protosol-go/metadata"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Message header contains the counts of required readonly and signatures
type MessageHeader struct {
	state                       protoimpl.MessageState `protogen:"open.v1"`
	NumRequiredSignatures       uint32                 `protobuf:"varint,1,opt,name=num_required_signatures,json=numRequiredSignatures,proto3" json:"num_required_signatures,omitempty"`
	NumReadonlySignedAccounts   uint32                 `protobuf:"varint,2,opt,name=num_readonly_signed_accounts,json=numReadonlySignedAccounts,proto3" json:"num_readonly_signed_accounts,omitempty"`
	NumReadonlyUnsignedAccounts uint32                 `protobuf:"varint,3,opt,name=num_readonly_unsigned_accounts,json=numReadonlyUnsignedAccounts,proto3" json:"num_readonly_unsigned_accounts,omitempty"`
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *MessageHeader) Reset() {
	*x = MessageHeader{}
	mi := &file_txn_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageHeader) ProtoMessage() {}

func (x *MessageHeader) ProtoReflect() protoreflect.Message {
	mi := &file_txn_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageHeader.ProtoReflect.Descriptor instead.
func (*MessageHeader) Descriptor() ([]byte, []int) {
	return file_txn_proto_rawDescGZIP(), []int{0}
}

func (x *MessageHeader) GetNumRequiredSignatures() uint32 {
	if x != nil {
		return x.NumRequiredSignatures
	}
	return 0
}

func (x *MessageHeader) GetNumReadonlySignedAccounts() uint32 {
	if x != nil {
		return x.NumReadonlySignedAccounts
	}
	return 0
}

func (x *MessageHeader) GetNumReadonlyUnsignedAccounts() uint32 {
	if x != nil {
		return x.NumReadonlyUnsignedAccounts
	}
	return 0
}

// The instruction a transaction executes
type CompiledInstruction struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Index into the message pubkey array
	ProgramIdIndex uint32 `protobuf:"varint,1,opt,name=program_id_index,json=programIdIndex,proto3" json:"program_id_index,omitempty"`
	// Indexes into the message pubkey array
	Accounts      []uint32 `protobuf:"varint,2,rep,packed,name=accounts,proto3" json:"accounts,omitempty"`
	Data          []byte   `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompiledInstruction) Reset() {
	*x = CompiledInstruction{}
	mi := &file_txn_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompiledInstruction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompiledInstruction) ProtoMessage() {}

func (x *CompiledInstruction) ProtoReflect() protoreflect.Message {
	mi := &file_txn_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompiledInstruction.ProtoReflect.Descriptor instead.
func (*CompiledInstruction) Descriptor() ([]byte, []int) {
	return file_txn_proto_rawDescGZIP(), []int{1}
}

func (x *CompiledInstruction) GetProgramIdIndex() uint32 {
	if x != nil {
		return x.ProgramIdIndex
	}
	return 0
}

func (x *CompiledInstruction) GetAccounts() []uint32 {
	if x != nil {
		return x.Accounts
	}
	return nil
}

func (x *CompiledInstruction) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// List of address table lookups used to load additional accounts for a transaction
type MessageAddressTableLookup struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AccountKey      []byte                 `protobuf:"bytes,1,opt,name=account_key,json=accountKey,proto3" json:"account_key,omitempty"`
	WritableIndexes []uint32               `protobuf:"varint,2,rep,packed,name=writable_indexes,json=writableIndexes,proto3" json:"writable_indexes,omitempty"`
	ReadonlyIndexes []uint32               `protobuf:"varint,3,rep,packed,name=readonly_indexes,json=readonlyIndexes,proto3" json:"readonly_indexes,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MessageAddressTableLookup) Reset() {
	*x = MessageAddressTableLookup{}
	mi := &file_txn_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageAddressTableLookup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageAddressTableLookup) ProtoMessage() {}

func (x *MessageAddressTableLookup) ProtoReflect() protoreflect.Message {
	mi := &file_txn_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageAddressTableLookup.ProtoReflect.Descriptor instead.
func (*MessageAddressTableLookup) Descriptor() ([]byte, []int) {
	return file_txn_proto_rawDescGZIP(), []int{2}
}

func (x *MessageAddressTableLookup) GetAccountKey() []byte {
	if x != nil {
		return x.AccountKey
	}
	return nil
}

func (x *MessageAddressTableLookup) GetWritableIndexes() []uint32 {
	if x != nil {
		return x.WritableIndexes
	}
	return nil
}

func (x *MessageAddressTableLookup) GetReadonlyIndexes() []uint32 {
	if x != nil {
		return x.ReadonlyIndexes
	}
	return nil
}

// Message contains the transaction data
type TransactionMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether this is a legacy message or not
	IsLegacy bool           `protobuf:"varint,1,opt,name=is_legacy,json=isLegacy,proto3" json:"is_legacy,omitempty"`
	Header   *MessageHeader `protobuf:"bytes,2,opt,name=header,proto3" json:"header,omitempty"`
	// Vector of pubkeys
	AccountKeys [][]byte `protobuf:"bytes,3,rep,name=account_keys,json=accountKeys,proto3" json:"account_keys,omitempty"`
	// Recent blockhash provided in message
	RecentBlockhash []byte `protobuf:"bytes,5,opt,name=recent_blockhash,json=recentBlockhash,proto3" json:"recent_blockhash,omitempty"`
	// The instructions this transaction executes
	Instructions []*CompiledInstruction `protobuf:"bytes,6,rep,name=instructions,proto3" json:"instructions,omitempty"`
	// Not available in legacy message
	AddressTableLookups []*MessageAddressTableLookup `protobuf:"bytes,7,rep,name=address_table_lookups,json=addressTableLookups,proto3" json:"address_table_lookups,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *TransactionMessage) Reset() {
	*x = TransactionMessage{}
	mi := &file_txn_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionMessage) ProtoMessage() {}

func (x *TransactionMessage) ProtoReflect() protoreflect.Message {
	mi := &file_txn_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionMessage.ProtoReflect.Descriptor instead.
func (*TransactionMessage) Descriptor() ([]byte, []int) {
	return file_txn_proto_rawDescGZIP(), []int{3}
}

func (x *TransactionMessage) GetIsLegacy() bool {
	if x != nil {
		return x.IsLegacy
	}
	return false
}

func (x *TransactionMessage) GetHeader() *MessageHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *TransactionMessage) GetAccountKeys() [][]byte {
	if x != nil {
		return x.AccountKeys
	}
	return nil
}

func (x *TransactionMessage) GetRecentBlockhash() []byte {
	if x != nil {
		return x.RecentBlockhash
	}
	return nil
}

func (x *TransactionMessage) GetInstructions() []*CompiledInstruction {
	if x != nil {
		return x.Instructions
	}
	return nil
}

func (x *TransactionMessage) GetAddressTableLookups() []*MessageAddressTableLookup {
	if x != nil {
		return x.AddressTableLookups
	}
	return nil
}

// A valid verified transaction
type SanitizedTransaction struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The transaction information
	Message *TransactionMessage `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	// The message hash
	MessageHash []byte `protobuf:"bytes,2,opt,name=message_hash,json=messageHash,proto3" json:"message_hash,omitempty"`
	// The signatures needed in the transaction
	Signatures    [][]byte `protobuf:"bytes,4,rep,name=signatures,proto3" json:"signatures,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SanitizedTransaction) Reset() {
	*x = SanitizedTransaction{}
	mi := &file_txn_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SanitizedTransaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SanitizedTransaction) ProtoMessage() {}

func (x *SanitizedTransaction) ProtoReflect() protoreflect.Message {
	mi := &file_txn_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SanitizedTransaction.ProtoReflect.Descriptor instead.
func (*SanitizedTransaction) Descriptor() ([]byte, []int) {
	return file_txn_proto_rawDescGZIP(), []int{4}
}

func (x *SanitizedTransaction) GetMessage() *TransactionMessage {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *SanitizedTransaction) GetMessageHash() []byte {
	if x != nil {
		return x.MessageHash
	}
	return nil
}

func (x *SanitizedTransaction) GetSignatures() [][]byte {
	if x != nil {
		return x.Signatures
	}
	return nil
}

// This Transaction context be used to fuzz either `load_execute_and_commit_transactions`,
// `load_and_execute_transactions` in `bank.rs` or `load_and_execute_sanitized_transactions`
// in `svm/transaction_processor.rs`
type TxnContext struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The transaction data
	Tx *SanitizedTransaction `protobuf:"bytes,1,opt,name=tx,proto3" json:"tx,omitempty"`
	// Data associated with transaction accounts, sysvars, etc.
	AccountSharedData []*context.AcctState `protobuf:"bytes,2,rep,name=account_shared_data,json=accountSharedData,proto3" json:"account_shared_data,omitempty"`
	// Up to 300 (actually 301) most recent blockhashes (ordered from oldest to newest)
	BlockhashQueue [][]byte              `protobuf:"bytes,3,rep,name=blockhash_queue,json=blockhashQueue,proto3" json:"blockhash_queue,omitempty"`
	EpochCtx       *context.EpochContext `protobuf:"bytes,4,opt,name=epoch_ctx,json=epochCtx,proto3" json:"epoch_ctx,omitempty"`
	SlotCtx        *context.SlotContext  `protobuf:"bytes,5,opt,name=slot_ctx,json=slotCtx,proto3" json:"slot_ctx,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TxnContext) Reset() {
	*x = TxnContext{}
	mi := &file_txn_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TxnContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxnContext) ProtoMessage() {}

func (x *TxnContext) ProtoReflect() protoreflect.Message {
	mi := &file_txn_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxnContext.ProtoReflect.Descriptor instead.
func (*TxnContext) Descriptor() ([]byte, []int) {
	return file_txn_proto_rawDescGZIP(), []int{5}
}

func (x *TxnContext) GetTx() *SanitizedTransaction {
	if x != nil {
		return x.Tx
	}
	return nil
}

func (x *TxnContext) GetAccountSharedData() []*context.AcctState {
	if x != nil {
		return x.AccountSharedData
	}
	return nil
}

func (x *TxnContext) GetBlockhashQueue() [][]byte {
	if x != nil {
		return x.BlockhashQueue
	}
	return nil
}

func (x *TxnContext) GetEpochCtx() *context.EpochContext {
	if x != nil {
		return x.EpochCtx
	}
	return nil
}

func (x *TxnContext) GetSlotCtx() *context.SlotContext {
	if x != nil {
		return x.SlotCtx
	}
	return nil
}

// The resulting state of an account after a transaction
type ResultingState struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AcctStates      []*context.AcctState   `protobuf:"bytes,1,rep,name=acct_states,json=acctStates,proto3" json:"acct_states,omitempty"`
	RentDebits      []*RentDebits          `protobuf:"bytes,2,rep,name=rent_debits,json=rentDebits,proto3" json:"rent_debits,omitempty"`
	TransactionRent uint64                 `protobuf:"varint,3,opt,name=transaction_rent,json=transactionRent,proto3" json:"transaction_rent,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ResultingState) Reset() {
	*x = ResultingState{}
	mi := &file_txn_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResultingState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResultingState) ProtoMessage() {}

func (x *ResultingState) ProtoReflect() protoreflect.Message {
	mi := &file_txn_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResultingState.ProtoReflect.Descriptor instead.
func (*ResultingState) Descriptor() ([]byte, []int) {
	return file_txn_proto_rawDescGZIP(), []int{6}
}

func (x *ResultingState) GetAcctStates() []*context.AcctState {
	if x != nil {
		return x.AcctStates
	}
	return nil
}

func (x *ResultingState) GetRentDebits() []*RentDebits {
	if x != nil {
		return x.RentDebits
	}
	return nil
}

func (x *ResultingState) GetTransactionRent() uint64 {
	if x != nil {
		return x.TransactionRent
	}
	return 0
}

// The rent state for an account after a transaction
type RentDebits struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pubkey        []byte                 `protobuf:"bytes,1,opt,name=pubkey,proto3" json:"pubkey,omitempty"`
	RentCollected int64                  `protobuf:"varint,2,opt,name=rent_collected,json=rentCollected,proto3" json:"rent_collected,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RentDebits) Reset() {
	*x = RentDebits{}
	mi := &file_txn_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RentDebits) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RentDebits) ProtoMessage() {}

func (x *RentDebits) ProtoReflect() protoreflect.Message {
	mi := &file_txn_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RentDebits.ProtoReflect.Descriptor instead.
func (*RentDebits) Descriptor() ([]byte, []int) {
	return file_txn_proto_rawDescGZIP(), []int{7}
}

func (x *RentDebits) GetPubkey() []byte {
	if x != nil {
		return x.Pubkey
	}
	return nil
}

func (x *RentDebits) GetRentCollected() int64 {
	if x != nil {
		return x.RentCollected
	}
	return 0
}

type FeeDetails struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	TransactionFee    uint64                 `protobuf:"varint,1,opt,name=transaction_fee,json=transactionFee,proto3" json:"transaction_fee,omitempty"`
	PrioritizationFee uint64                 `protobuf:"varint,2,opt,name=prioritization_fee,json=prioritizationFee,proto3" json:"prioritization_fee,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *FeeDetails) Reset() {
	*x = FeeDetails{}
	mi := &file_txn_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeeDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeeDetails) ProtoMessage() {}

func (x *FeeDetails) ProtoReflect() protoreflect.Message {
	mi := &file_txn_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeeDetails.ProtoReflect.Descriptor instead.
func (*FeeDetails) Descriptor() ([]byte, []int) {
	return file_txn_proto_rawDescGZIP(), []int{8}
}

func (x *FeeDetails) GetTransactionFee() uint64 {
	if x != nil {
		return x.TransactionFee
	}
	return 0
}

func (x *FeeDetails) GetPrioritizationFee() uint64 {
	if x != nil {
		return x.PrioritizationFee
	}
	return 0
}

// The execution results for a transaction
type TxnResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether this transaction was executed
	Executed bool `protobuf:"varint,1,opt,name=executed,proto3" json:"executed,omitempty"`
	// Whether there was a sanitization error
	SanitizationError bool `protobuf:"varint,2,opt,name=sanitization_error,json=sanitizationError,proto3" json:"sanitization_error,omitempty"`
	// The state of each account after the transaction
	ResultingState *ResultingState `protobuf:"bytes,3,opt,name=resulting_state,json=resultingState,proto3" json:"resulting_state,omitempty"`
	Rent           uint64          `protobuf:"varint,4,opt,name=rent,proto3" json:"rent,omitempty"`
	// If an executed transaction has no error
	IsOk bool `protobuf:"varint,5,opt,name=is_ok,json=isOk,proto3" json:"is_ok,omitempty"`
	// The transaction status (error code)
	Status uint32 `protobuf:"varint,6,opt,name=status,proto3" json:"status,omitempty"`
	// The instruction error, if any
	InstructionError uint32 `protobuf:"varint,7,opt,name=instruction_error,json=instructionError,proto3" json:"instruction_error,omitempty"`
	// The instruction error index, if any
	InstructionErrorIndex uint32 `protobuf:"varint,8,opt,name=instruction_error_index,json=instructionErrorIndex,proto3" json:"instruction_error_index,omitempty"`
	// Custom error, if any
	CustomError uint32 `protobuf:"varint,9,opt,name=custom_error,json=customError,proto3" json:"custom_error,omitempty"`
	// The return data from this transaction, if any
	ReturnData []byte `protobuf:"bytes,10,opt,name=return_data,json=returnData,proto3" json:"return_data,omitempty"`
	// Number of executed compute units
	ExecutedUnits uint64 `protobuf:"varint,11,opt,name=executed_units,json=executedUnits,proto3" json:"executed_units,omitempty"`
	// The collected fees in this transaction
	FeeDetails *FeeDetails `protobuf:"bytes,12,opt,name=fee_details,json=feeDetails,proto3" json:"fee_details,omitempty"`
	// Loaded accounts data size
	LoadedAccountsDataSize uint64 `protobuf:"varint,13,opt,name=loaded_accounts_data_size,json=loadedAccountsDataSize,proto3" json:"loaded_accounts_data_size,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *TxnResult) Reset() {
	*x = TxnResult{}
	mi := &file_txn_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TxnResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxnResult) ProtoMessage() {}

func (x *TxnResult) ProtoReflect() protoreflect.Message {
	mi := &file_txn_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxnResult.ProtoReflect.Descriptor instead.
func (*TxnResult) Descriptor() ([]byte, []int) {
	return file_txn_proto_rawDescGZIP(), []int{9}
}

func (x *TxnResult) GetExecuted() bool {
	if x != nil {
		return x.Executed
	}
	return false
}

func (x *TxnResult) GetSanitizationError() bool {
	if x != nil {
		return x.SanitizationError
	}
	return false
}

func (x *TxnResult) GetResultingState() *ResultingState {
	if x != nil {
		return x.ResultingState
	}
	return nil
}

func (x *TxnResult) GetRent() uint64 {
	if x != nil {
		return x.Rent
	}
	return 0
}

func (x *TxnResult) GetIsOk() bool {
	if x != nil {
		return x.IsOk
	}
	return false
}

func (x *TxnResult) GetStatus() uint32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *TxnResult) GetInstructionError() uint32 {
	if x != nil {
		return x.InstructionError
	}
	return 0
}

func (x *TxnResult) GetInstructionErrorIndex() uint32 {
	if x != nil {
		return x.InstructionErrorIndex
	}
	return 0
}

func (x *TxnResult) GetCustomError() uint32 {
	if x != nil {
		return x.CustomError
	}
	return 0
}

func (x *TxnResult) GetReturnData() []byte {
	if x != nil {
		return x.ReturnData
	}
	return nil
}

func (x *TxnResult) GetExecutedUnits() uint64 {
	if x != nil {
		return x.ExecutedUnits
	}
	return 0
}

func (x *TxnResult) GetFeeDetails() *FeeDetails {
	if x != nil {
		return x.FeeDetails
	}
	return nil
}

func (x *TxnResult) GetLoadedAccountsDataSize() uint64 {
	if x != nil {
		return x.LoadedAccountsDataSize
	}
	return 0
}

// Txn fixtures
type TxnFixture struct {
	state    protoimpl.MessageState    `protogen:"open.v1"`
	Metadata *metadata.FixtureMetadata `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	// Context
	Input *TxnContext `protobuf:"bytes,2,opt,name=input,proto3" json:"input,omitempty"`
	// Effects
	Output        *TxnResult `protobuf:"bytes,3,opt,name=output,proto3" json:"output,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TxnFixture) Reset() {
	*x = TxnFixture{}
	mi := &file_txn_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TxnFixture) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxnFixture) ProtoMessage() {}

func (x *TxnFixture) ProtoReflect() protoreflect.Message {
	mi := &file_txn_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxnFixture.ProtoReflect.Descriptor instead.
func (*TxnFixture) Descriptor() ([]byte, []int) {
	return file_txn_proto_rawDescGZIP(), []int{10}
}

func (x *TxnFixture) GetMetadata() *metadata.FixtureMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *TxnFixture) GetInput() *TxnContext {
	if x != nil {
		return x.Input
	}
	return nil
}

func (x *TxnFixture) GetOutput() *TxnResult {
	if x != nil {
		return x.Output
	}
	return nil
}

var File_txn_proto protoreflect.FileDescriptor

const file_txn_proto_rawDesc = "" +
	"\n" +
	"\ttxn.proto\x12\x16org.solana.sealevel.v1\x1a\rcontext.proto\x1a\x0emetadata.proto\"\xcd\x01\n" +
	"\rMessageHeader\x126\n" +
	"\x17num_required_signatures\x18\x01 \x01(\rR\x15numRequiredSignatures\x12?\n" +
	"\x1cnum_readonly_signed_accounts\x18\x02 \x01(\rR\x19numReadonlySignedAccounts\x12C\n" +
	"\x1enum_readonly_unsigned_accounts\x18\x03 \x01(\rR\x1bnumReadonlyUnsignedAccounts\"o\n" +
	"\x13CompiledInstruction\x12(\n" +
	"\x10program_id_index\x18\x01 \x01(\rR\x0eprogramIdIndex\x12\x1a\n" +
	"\baccounts\x18\x02 \x03(\rR\baccounts\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\"\x92\x01\n" +
	"\x19MessageAddressTableLookup\x12\x1f\n" +
	"\vaccount_key\x18\x01 \x01(\fR\n" +
	"accountKey\x12)\n" +
	"\x10writable_indexes\x18\x02 \x03(\rR\x0fwritableIndexes\x12)\n" +
	"\x10readonly_indexes\x18\x03 \x03(\rR\x0freadonlyIndexes\"\xf6\x02\n" +
	"\x12TransactionMessage\x12\x1b\n" +
	"\tis_legacy\x18\x01 \x01(\bR\bisLegacy\x12=\n" +
	"\x06header\x18\x02 \x01(\v2%.org.solana.sealevel.v1.MessageHeaderR\x06header\x12!\n" +
	"\faccount_keys\x18\x03 \x03(\fR\vaccountKeys\x12)\n" +
	"\x10recent_blockhash\x18\x05 \x01(\fR\x0frecentBlockhash\x12O\n" +
	"\finstructions\x18\x06 \x03(\v2+.org.solana.sealevel.v1.CompiledInstructionR\finstructions\x12e\n" +
	"\x15address_table_lookups\x18\a \x03(\v21.org.solana.sealevel.v1.MessageAddressTableLookupR\x13addressTableLookups\"\x9f\x01\n" +
	"\x14SanitizedTransaction\x12D\n" +
	"\amessage\x18\x01 \x01(\v2*.org.solana.sealevel.v1.TransactionMessageR\amessage\x12!\n" +
	"\fmessage_hash\x18\x02 \x01(\fR\vmessageHash\x12\x1e\n" +
	"\n" +
	"signatures\x18\x04 \x03(\fR\n" +
	"signatures\"\xc9\x02\n" +
	"\n" +
	"TxnContext\x12<\n" +
	"\x02tx\x18\x01 \x01(\v2,.org.solana.sealevel.v1.SanitizedTransactionR\x02tx\x12Q\n" +
	"\x13account_shared_data\x18\x02 \x03(\v2!.org.solana.sealevel.v1.AcctStateR\x11accountSharedData\x12'\n" +
	"\x0fblockhash_queue\x18\x03 \x03(\fR\x0eblockhashQueue\x12A\n" +
	"\tepoch_ctx\x18\x04 \x01(\v2$.org.solana.sealevel.v1.EpochContextR\bepochCtx\x12>\n" +
	"\bslot_ctx\x18\x05 \x01(\v2#.org.solana.sealevel.v1.SlotContextR\aslotCtx\"\xc4\x01\n" +
	"\x0eResultingState\x12B\n" +
	"\vacct_states\x18\x01 \x03(\v2!.org.solana.sealevel.v1.AcctStateR\n" +
	"acctStates\x12C\n" +
	"\vrent_debits\x18\x02 \x03(\v2\".org.solana.sealevel.v1.RentDebitsR\n" +
	"rentDebits\x12)\n" +
	"\x10transaction_rent\x18\x03 \x01(\x04R\x0ftransactionRent\"K\n" +
	"\n" +
	"RentDebits\x12\x16\n" +
	"\x06pubkey\x18\x01 \x01(\fR\x06pubkey\x12%\n" +
	"\x0erent_collected\x18\x02 \x01(\x03R\rrentCollected\"d\n" +
	"\n" +
	"FeeDetails\x12'\n" +
	"\x0ftransaction_fee\x18\x01 \x01(\x04R\x0etransactionFee\x12-\n" +
	"\x12prioritization_fee\x18\x02 \x01(\x04R\x11prioritizationFee\"\xb8\x04\n" +
	"\tTxnResult\x12\x1a\n" +
	"\bexecuted\x18\x01 \x01(\bR\bexecuted\x12-\n" +
	"\x12sanitization_error\x18\x02 \x01(\bR\x11sanitizationError\x12O\n" +
	"\x0fresulting_state\x18\x03 \x01(\v2&.org.solana.sealevel.v1.ResultingStateR\x0eresultingState\x12\x12\n" +
	"\x04rent\x18\x04 \x01(\x04R\x04rent\x12\x13\n" +
	"\x05is_ok\x18\x05 \x01(\bR\x04isOk\x12\x16\n" +
	"\x06status\x18\x06 \x01(\rR\x06status\x12+\n" +
	"\x11instruction_error\x18\a \x01(\rR\x10instructionError\x126\n" +
	"\x17instruction_error_index\x18\b \x01(\rR\x15instructionErrorIndex\x12!\n" +
	"\fcustom_error\x18\t \x01(\rR\vcustomError\x12\x1f\n" +
	"\vreturn_data\x18\n" +
	" \x01(\fR\n" +
	"returnData\x12%\n" +
	"\x0eexecuted_units\x18\v \x01(\x04R\rexecutedUnits\x12C\n" +
	"\vfee_details\x18\f \x01(\v2\".org.solana.sealevel.v1.FeeDetailsR\n" +
	"feeDetails\x129\n" +
	"\x19loaded_accounts_data_size\x18\r \x01(\x04R\x16loadedAccountsDataSize\"\xc6\x01\n" +
	"\n" +
	"TxnFixture\x12C\n" +
	"\bmetadata\x18\x01 \x01(\v2'.org.solana.sealevel.v1.FixtureMetadataR\bmetadata\x128\n" +
	"\x05input\x18\x02 \x01(\v2\".org.solana.sealevel.v1.TxnContextR\x05input\x129\n" +
	"\x06output\x18\x03 \x01(\v2!.org.solana.sealevel.v1.TxnResultR\x06outputb\x06proto3"

var (
	file_txn_proto_rawDescOnce sync.Once
	file_txn_proto_rawDescData []byte
)

func file_txn_proto_rawDescGZIP() []byte {
	file_txn_proto_rawDescOnce.Do(func() {
		file_txn_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_txn_proto_rawDesc), len(file_txn_proto_rawDesc)))
	})
	return file_txn_proto_rawDescData
}

var file_txn_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_txn_proto_goTypes = []any{
	(*MessageHeader)(nil),             // 0: org.solana.sealevel.v1.MessageHeader
	(*CompiledInstruction)(nil),       // 1: org.solana.sealevel.v1.CompiledInstruction
	(*MessageAddressTableLookup)(nil), // 2: org.solana.sealevel.v1.MessageAddressTableLookup
	(*TransactionMessage)(nil),        // 3: org.solana.sealevel.v1.TransactionMessage
	(*SanitizedTransaction)(nil),      // 4: org.solana.sealevel.v1.SanitizedTransaction
	(*TxnContext)(nil),                // 5: org.solana.sealevel.v1.TxnContext
	(*ResultingState)(nil),            // 6: org.solana.sealevel.v1.ResultingState
	(*RentDebits)(nil),                // 7: org.solana.sealevel.v1.RentDebits
	(*FeeDetails)(nil),                // 8: org.solana.sealevel.v1.FeeDetails
	(*TxnResult)(nil),                 // 9: org.solana.sealevel.v1.TxnResult
	(*TxnFixture)(nil),                // 10: org.solana.sealevel.v1.TxnFixture
	(*context.AcctState)(nil),         // 11: org.solana.sealevel.v1.AcctState
	(*context.EpochContext)(nil),      // 12: org.solana.sealevel.v1.EpochContext
	(*context.SlotContext)(nil),       // 13: org.solana.sealevel.v1.SlotContext
	(*metadata.FixtureMetadata)(nil),  // 14: org.solana.sealevel.v1.FixtureMetadata
}
var file_txn_proto_depIdxs = []int32{
	0,  // 0: org.solana.sealevel.v1.TransactionMessage.header:type_name -> org.solana.sealevel.v1.MessageHeader
	1,  // 1: org.solana.sealevel.v1.TransactionMessage.instructions:type_name -> org.solana.sealevel.v1.CompiledInstruction
	2,  // 2: org.solana.sealevel.v1.TransactionMessage.address_table_lookups:type_name -> org.solana.sealevel.v1.MessageAddressTableLookup
	3,  // 3: org.solana.sealevel.v1.SanitizedTransaction.message:type_name -> org.solana.sealevel.v1.TransactionMessage
	4,  // 4: org.solana.sealevel.v1.TxnContext.tx:type_name -> org.solana.sealevel.v1.SanitizedTransaction
	11, // 5: org.solana.sealevel.v1.TxnContext.account_shared_data:type_name -> org.solana.sealevel.v1.AcctState
	12, // 6: org.solana.sealevel.v1.TxnContext.epoch_ctx:type_name -> org.solana.sealevel.v1.EpochContext
	13, // 7: org.solana.sealevel.v1.TxnContext.slot_ctx:type_name -> org.solana.sealevel.v1.SlotContext
	11, // 8: org.solana.sealevel.v1.ResultingState.acct_states:type_name -> org.solana.sealevel.v1.AcctState
	7,  // 9: org.solana.sealevel.v1.ResultingState.rent_debits:type_name -> org.solana.sealevel.v1.RentDebits
	6,  // 10: org.solana.sealevel.v1.TxnResult.resulting_state:type_name -> org.solana.sealevel.v1.ResultingState
	8,  // 11: org.solana.sealevel.v1.TxnResult.fee_details:type_name -> org.solana.sealevel.v1.FeeDetails
	14, // 12: org.solana.sealevel.v1.TxnFixture.metadata:type_name -> org.solana.sealevel.v1.FixtureMetadata
	5,  // 13: org.solana.sealevel.v1.TxnFixture.input:type_name -> org.solana.sealevel.v1.TxnContext
	9,  // 14: org.solana.sealevel.v1.TxnFixture.output:type_name -> org.solana.sealevel.v1.TxnResult
	15, // [15:15] is the sub-list for method output_type
	15, // [15:15] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_txn_proto_init() }
func file_txn_proto_init() {
	if File_txn_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_txn_proto_rawDesc), len(file_txn_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_txn_proto_goTypes,
		DependencyIndexes: file_txn_proto_depIdxs,
		MessageInfos:      file_txn_proto_msgTypes,
	}.Build()
	File_txn_proto = out.File
	file_txn_proto_goTypes = nil
	file_txn_proto_depIdxs = nil
}
