// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: pack.proto

package pack

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	context "github.com/Overclock-Validator/mithril/pkg/protosol-go/context"
	metadata "github.com/Overclock-Validator/mithril/pkg/protosol-go/metadata"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PackComputeBudgetContext struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstrDatas    [][]byte               `protobuf:"bytes,1,rep,name=instr_datas,json=instrDatas,proto3" json:"instr_datas,omitempty"`
	Features      *context.FeatureSet    `protobuf:"bytes,2,opt,name=features,proto3" json:"features,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PackComputeBudgetContext) Reset() {
	*x = PackComputeBudgetContext{}
	mi := &file_pack_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PackComputeBudgetContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PackComputeBudgetContext) ProtoMessage() {}

func (x *PackComputeBudgetContext) ProtoReflect() protoreflect.Message {
	mi := &file_pack_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PackComputeBudgetContext.ProtoReflect.Descriptor instead.
func (*PackComputeBudgetContext) Descriptor() ([]byte, []int) {
	return file_pack_proto_rawDescGZIP(), []int{0}
}

func (x *PackComputeBudgetContext) GetInstrDatas() [][]byte {
	if x != nil {
		return x.InstrDatas
	}
	return nil
}

func (x *PackComputeBudgetContext) GetFeatures() *context.FeatureSet {
	if x != nil {
		return x.Features
	}
	return nil
}

type PackComputeBudgetEffects struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ComputeUnitLimit uint64                 `protobuf:"varint,1,opt,name=compute_unit_limit,json=computeUnitLimit,proto3" json:"compute_unit_limit,omitempty"`
	Rewards          uint64                 `protobuf:"varint,2,opt,name=rewards,proto3" json:"rewards,omitempty"`
	HeapSz           uint32                 `protobuf:"varint,3,opt,name=heap_sz,json=heapSz,proto3" json:"heap_sz,omitempty"`
	LoadedAcctDataSz uint32                 `protobuf:"varint,4,opt,name=loaded_acct_data_sz,json=loadedAcctDataSz,proto3" json:"loaded_acct_data_sz,omitempty"`
	// To prevent empty effects when encoding a "skipped" effects
	IsEmpty       uint32 `protobuf:"varint,5,opt,name=is_empty,json=isEmpty,proto3" json:"is_empty,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PackComputeBudgetEffects) Reset() {
	*x = PackComputeBudgetEffects{}
	mi := &file_pack_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PackComputeBudgetEffects) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PackComputeBudgetEffects) ProtoMessage() {}

func (x *PackComputeBudgetEffects) ProtoReflect() protoreflect.Message {
	mi := &file_pack_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PackComputeBudgetEffects.ProtoReflect.Descriptor instead.
func (*PackComputeBudgetEffects) Descriptor() ([]byte, []int) {
	return file_pack_proto_rawDescGZIP(), []int{1}
}

func (x *PackComputeBudgetEffects) GetComputeUnitLimit() uint64 {
	if x != nil {
		return x.ComputeUnitLimit
	}
	return 0
}

func (x *PackComputeBudgetEffects) GetRewards() uint64 {
	if x != nil {
		return x.Rewards
	}
	return 0
}

func (x *PackComputeBudgetEffects) GetHeapSz() uint32 {
	if x != nil {
		return x.HeapSz
	}
	return 0
}

func (x *PackComputeBudgetEffects) GetLoadedAcctDataSz() uint32 {
	if x != nil {
		return x.LoadedAcctDataSz
	}
	return 0
}

func (x *PackComputeBudgetEffects) GetIsEmpty() uint32 {
	if x != nil {
		return x.IsEmpty
	}
	return 0
}

type PackComputeBudgetFixture struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Metadata      *metadata.FixtureMetadata `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Input         *PackComputeBudgetContext `protobuf:"bytes,2,opt,name=input,proto3" json:"input,omitempty"`
	Output        *PackComputeBudgetEffects `protobuf:"bytes,3,opt,name=output,proto3" json:"output,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PackComputeBudgetFixture) Reset() {
	*x = PackComputeBudgetFixture{}
	mi := &file_pack_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PackComputeBudgetFixture) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PackComputeBudgetFixture) ProtoMessage() {}

func (x *PackComputeBudgetFixture) ProtoReflect() protoreflect.Message {
	mi := &file_pack_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PackComputeBudgetFixture.ProtoReflect.Descriptor instead.
func (*PackComputeBudgetFixture) Descriptor() ([]byte, []int) {
	return file_pack_proto_rawDescGZIP(), []int{2}
}

func (x *PackComputeBudgetFixture) GetMetadata() *metadata.FixtureMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *PackComputeBudgetFixture) GetInput() *PackComputeBudgetContext {
	if x != nil {
		return x.Input
	}
	return nil
}

func (x *PackComputeBudgetFixture) GetOutput() *PackComputeBudgetEffects {
	if x != nil {
		return x.Output
	}
	return nil
}

var File_pack_proto protoreflect.FileDescriptor

const file_pack_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"pack.proto\x12\x16org.solana.sealevel.v1\x1a\x0emetadata.proto\x1a\rcontext.proto\"{\n" +
	"\x18PackComputeBudgetContext\x12\x1f\n" +
	"\vinstr_datas\x18\x01 \x03(\fR\n" +
	"instrDatas\x12>\n" +
	"\bfeatures\x18\x02 \x01(\v2\".org.solana.sealevel.v1.FeatureSetR\bfeatures\"\xc5\x01\n" +
	"\x18PackComputeBudgetEffects\x12,\n" +
	"\x12compute_unit_limit\x18\x01 \x01(\x04R\x10computeUnitLimit\x12\x18\n" +
	"\arewards\x18\x02 \x01(\x04R\arewards\x12\x17\n" +
	"\aheap_sz\x18\x03 \x01(\rR\x06heapSz\x12-\n" +
	"\x13loaded_acct_data_sz\x18\x04 \x01(\rR\x10loadedAcctDataSz\x12\x19\n" +
	"\bis_empty\x18\x05 \x01(\rR\aisEmpty\"\xf1\x01\n" +
	"\x18PackComputeBudgetFixture\x12C\n" +
	"\bmetadata\x18\x01 \x01(\v2'.org.solana.sealevel.v1.FixtureMetadataR\bmetadata\x12F\n" +
	"\x05input\x18\x02 \x01(\v20.org.solana.sealevel.v1.PackComputeBudgetContextR\x05input\x12H\n" +
	"\x06output\x18\x03 \x01(\v20.org.solana.sealevel.v1.PackComputeBudgetEffectsR\x06outputb\x06proto3"

var (
	file_pack_proto_rawDescOnce sync.Once
	file_pack_proto_rawDescData []byte
)

func file_pack_proto_rawDescGZIP() []byte {
	file_pack_proto_rawDescOnce.Do(func() {
		file_pack_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pack_proto_rawDesc), len(file_pack_proto_rawDesc)))
	})
	return file_pack_proto_rawDescData
}

var file_pack_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_pack_proto_goTypes = []any{
	(*PackComputeBudgetContext)(nil), // 0: org.solana.sealevel.v1.PackComputeBudgetContext
	(*PackComputeBudgetEffects)(nil), // 1: org.solana.sealevel.v1.PackComputeBudgetEffects
	(*PackComputeBudgetFixture)(nil), // 2: org.solana.sealevel.v1.PackComputeBudgetFixture
	(*context.FeatureSet)(nil),       // 3: org.solana.sealevel.v1.FeatureSet
	(*metadata.FixtureMetadata)(nil), // 4: org.solana.sealevel.v1.FixtureMetadata
}
var file_pack_proto_depIdxs = []int32{
	3, // 0: org.solana.sealevel.v1.PackComputeBudgetContext.features:type_name -> org.solana.sealevel.v1.FeatureSet
	4, // 1: org.solana.sealevel.v1.PackComputeBudgetFixture.metadata:type_name -> org.solana.sealevel.v1.FixtureMetadata
	0, // 2: org.solana.sealevel.v1.PackComputeBudgetFixture.input:type_name -> org.solana.sealevel.v1.PackComputeBudgetContext
	1, // 3: org.solana.sealevel.v1.PackComputeBudgetFixture.output:type_name -> org.solana.sealevel.v1.PackComputeBudgetEffects
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_pack_proto_init() }
func file_pack_proto_init() {
	if File_pack_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pack_proto_rawDesc), len(file_pack_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pack_proto_goTypes,
		DependencyIndexes: file_pack_proto_depIdxs,
		MessageInfos:      file_pack_proto_msgTypes,
	}.Build()
	File_pack_proto = out.File
	file_pack_proto_goTypes = nil
	file_pack_proto_depIdxs = nil
}
