// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: vm.proto

package vm

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	context "github.com/Overclock-Validator/mithril/pkg/protosol-go/context"
	invoke "github.com/Overclock-Validator/mithril/pkg/protosol-go/invoke"
	metadata "github.com/Overclock-Validator/mithril/pkg/protosol-go/metadata"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// We are only concerned with these error kinds as the syscall/VM fuzzers don't
// hit higher level error kinds (e.g., transaction errors)
type ErrKind int32

const (
	ErrKind_UNSPECIFIED ErrKind = 0
	ErrKind_EBPF        ErrKind = 1
	ErrKind_SYSCALL     ErrKind = 2
	ErrKind_INSTRUCTION ErrKind = 3
)

// Enum value maps for ErrKind.
var (
	ErrKind_name = map[int32]string{
		0: "UNSPECIFIED",
		1: "EBPF",
		2: "SYSCALL",
		3: "INSTRUCTION",
	}
	ErrKind_value = map[string]int32{
		"UNSPECIFIED": 0,
		"EBPF":        1,
		"SYSCALL":     2,
		"INSTRUCTION": 3,
	}
)

func (x ErrKind) Enum() *ErrKind {
	p := new(ErrKind)
	*p = x
	return p
}

func (x ErrKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrKind) Descriptor() protoreflect.EnumDescriptor {
	return file_vm_proto_enumTypes[0].Descriptor()
}

func (ErrKind) Type() protoreflect.EnumType {
	return &file_vm_proto_enumTypes[0]
}

func (x ErrKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrKind.Descriptor instead.
func (ErrKind) EnumDescriptor() ([]byte, []int) {
	return file_vm_proto_rawDescGZIP(), []int{0}
}

// Describes an input data region. Agave's memory mapping sets up a series of
// memory mapped regions, which combine to make the input data region.
type InputDataRegion struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Offset from the start of the input data segment (0x400000000)
	Offset uint64 `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	// Content of the memory region
	Content []byte `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	// If the memory region is writable or not
	IsWritable    bool `protobuf:"varint,3,opt,name=is_writable,json=isWritable,proto3" json:"is_writable,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InputDataRegion) Reset() {
	*x = InputDataRegion{}
	mi := &file_vm_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InputDataRegion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InputDataRegion) ProtoMessage() {}

func (x *InputDataRegion) ProtoReflect() protoreflect.Message {
	mi := &file_vm_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InputDataRegion.ProtoReflect.Descriptor instead.
func (*InputDataRegion) Descriptor() ([]byte, []int) {
	return file_vm_proto_rawDescGZIP(), []int{0}
}

func (x *InputDataRegion) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *InputDataRegion) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *InputDataRegion) GetIsWritable() bool {
	if x != nil {
		return x.IsWritable
	}
	return false
}

// Information sufficient to allow the fuzzer to generate a fd_vm_t context for
// execution inside the VM (excluding the instruction context).
//
// TODO: this currently only includes fields necessary for executing syscalls,
// executing sBPF code will require the rest of the fields in fd_vm_t to be set.
type VmContext struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Maximum heap size in bytes
	HeapMax uint64 `protobuf:"varint,1,opt,name=heap_max,json=heapMax,proto3" json:"heap_max,omitempty"`
	// Program read-only data
	Rodata []byte `protobuf:"bytes,2,opt,name=rodata,proto3" json:"rodata,omitempty"`
	// Offset of the text section from the start of the program rodata segment
	// (0x100000000)
	RodataTextSectionOffset uint64 `protobuf:"varint,3,opt,name=rodata_text_section_offset,json=rodataTextSectionOffset,proto3" json:"rodata_text_section_offset,omitempty"`
	// Length of the text section in the program rodata region, in bytes.
	RodataTextSectionLength uint64 `protobuf:"varint,4,opt,name=rodata_text_section_length,json=rodataTextSectionLength,proto3" json:"rodata_text_section_length,omitempty"`
	// Registers
	R0  uint64 `protobuf:"varint,6,opt,name=r0,proto3" json:"r0,omitempty"`
	R1  uint64 `protobuf:"varint,7,opt,name=r1,proto3" json:"r1,omitempty"`
	R2  uint64 `protobuf:"varint,8,opt,name=r2,proto3" json:"r2,omitempty"`
	R3  uint64 `protobuf:"varint,9,opt,name=r3,proto3" json:"r3,omitempty"`
	R4  uint64 `protobuf:"varint,10,opt,name=r4,proto3" json:"r4,omitempty"`
	R5  uint64 `protobuf:"varint,11,opt,name=r5,proto3" json:"r5,omitempty"`
	R6  uint64 `protobuf:"varint,12,opt,name=r6,proto3" json:"r6,omitempty"`
	R7  uint64 `protobuf:"varint,13,opt,name=r7,proto3" json:"r7,omitempty"`
	R8  uint64 `protobuf:"varint,14,opt,name=r8,proto3" json:"r8,omitempty"`
	R9  uint64 `protobuf:"varint,15,opt,name=r9,proto3" json:"r9,omitempty"`
	R10 uint64 `protobuf:"varint,16,opt,name=r10,proto3" json:"r10,omitempty"`
	R11 uint64 `protobuf:"varint,17,opt,name=r11,proto3" json:"r11,omitempty"`
	// for vm execution
	EntryPc uint64 `protobuf:"varint,20,opt,name=entry_pc,json=entryPc,proto3" json:"entry_pc,omitempty"`
	// Bitset of valid call destinations (in terms of pc).
	// This model is used by the Firedancer VM for CALL_IMMs
	CallWhitelist  []byte      `protobuf:"bytes,21,opt,name=call_whitelist,json=callWhitelist,proto3" json:"call_whitelist,omitempty"`
	TracingEnabled bool        `protobuf:"varint,22,opt,name=tracing_enabled,json=tracingEnabled,proto3" json:"tracing_enabled,omitempty"`
	ReturnData     *ReturnData `protobuf:"bytes,23,opt,name=return_data,json=returnData,proto3" json:"return_data,omitempty"`
	// SBPF version
	SbpfVersion   uint32 `protobuf:"varint,24,opt,name=sbpf_version,json=sbpfVersion,proto3" json:"sbpf_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VmContext) Reset() {
	*x = VmContext{}
	mi := &file_vm_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VmContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VmContext) ProtoMessage() {}

func (x *VmContext) ProtoReflect() protoreflect.Message {
	mi := &file_vm_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VmContext.ProtoReflect.Descriptor instead.
func (*VmContext) Descriptor() ([]byte, []int) {
	return file_vm_proto_rawDescGZIP(), []int{1}
}

func (x *VmContext) GetHeapMax() uint64 {
	if x != nil {
		return x.HeapMax
	}
	return 0
}

func (x *VmContext) GetRodata() []byte {
	if x != nil {
		return x.Rodata
	}
	return nil
}

func (x *VmContext) GetRodataTextSectionOffset() uint64 {
	if x != nil {
		return x.RodataTextSectionOffset
	}
	return 0
}

func (x *VmContext) GetRodataTextSectionLength() uint64 {
	if x != nil {
		return x.RodataTextSectionLength
	}
	return 0
}

func (x *VmContext) GetR0() uint64 {
	if x != nil {
		return x.R0
	}
	return 0
}

func (x *VmContext) GetR1() uint64 {
	if x != nil {
		return x.R1
	}
	return 0
}

func (x *VmContext) GetR2() uint64 {
	if x != nil {
		return x.R2
	}
	return 0
}

func (x *VmContext) GetR3() uint64 {
	if x != nil {
		return x.R3
	}
	return 0
}

func (x *VmContext) GetR4() uint64 {
	if x != nil {
		return x.R4
	}
	return 0
}

func (x *VmContext) GetR5() uint64 {
	if x != nil {
		return x.R5
	}
	return 0
}

func (x *VmContext) GetR6() uint64 {
	if x != nil {
		return x.R6
	}
	return 0
}

func (x *VmContext) GetR7() uint64 {
	if x != nil {
		return x.R7
	}
	return 0
}

func (x *VmContext) GetR8() uint64 {
	if x != nil {
		return x.R8
	}
	return 0
}

func (x *VmContext) GetR9() uint64 {
	if x != nil {
		return x.R9
	}
	return 0
}

func (x *VmContext) GetR10() uint64 {
	if x != nil {
		return x.R10
	}
	return 0
}

func (x *VmContext) GetR11() uint64 {
	if x != nil {
		return x.R11
	}
	return 0
}

func (x *VmContext) GetEntryPc() uint64 {
	if x != nil {
		return x.EntryPc
	}
	return 0
}

func (x *VmContext) GetCallWhitelist() []byte {
	if x != nil {
		return x.CallWhitelist
	}
	return nil
}

func (x *VmContext) GetTracingEnabled() bool {
	if x != nil {
		return x.TracingEnabled
	}
	return false
}

func (x *VmContext) GetReturnData() *ReturnData {
	if x != nil {
		return x.ReturnData
	}
	return nil
}

func (x *VmContext) GetSbpfVersion() uint32 {
	if x != nil {
		return x.SbpfVersion
	}
	return 0
}

// A single invocation of a syscall
type SyscallInvocation struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The sBPF function name of the syscall
	FunctionName []byte `protobuf:"bytes,1,opt,name=function_name,json=functionName,proto3" json:"function_name,omitempty"`
	// The initial portion of the heap, for example to store syscall inputs
	HeapPrefix []byte `protobuf:"bytes,2,opt,name=heap_prefix,json=heapPrefix,proto3" json:"heap_prefix,omitempty"`
	// The initial portion of the stack, for example to store syscall inputs
	StackPrefix   []byte `protobuf:"bytes,3,opt,name=stack_prefix,json=stackPrefix,proto3" json:"stack_prefix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyscallInvocation) Reset() {
	*x = SyscallInvocation{}
	mi := &file_vm_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyscallInvocation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyscallInvocation) ProtoMessage() {}

func (x *SyscallInvocation) ProtoReflect() protoreflect.Message {
	mi := &file_vm_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyscallInvocation.ProtoReflect.Descriptor instead.
func (*SyscallInvocation) Descriptor() ([]byte, []int) {
	return file_vm_proto_rawDescGZIP(), []int{2}
}

func (x *SyscallInvocation) GetFunctionName() []byte {
	if x != nil {
		return x.FunctionName
	}
	return nil
}

func (x *SyscallInvocation) GetHeapPrefix() []byte {
	if x != nil {
		return x.HeapPrefix
	}
	return nil
}

func (x *SyscallInvocation) GetStackPrefix() []byte {
	if x != nil {
		return x.StackPrefix
	}
	return nil
}

// Execution context for a VM Syscall execution.
type SyscallContext struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	VmCtx *VmContext             `protobuf:"bytes,1,opt,name=vm_ctx,json=vmCtx,proto3" json:"vm_ctx,omitempty"`
	// InflightInstruction - contain temporary fields that live for the duration of an instructions execution, and is needed if we have overhanging context from a previous instruction
	InstrCtx          *invoke.InstrContext `protobuf:"bytes,2,opt,name=instr_ctx,json=instrCtx,proto3" json:"instr_ctx,omitempty"`
	SyscallInvocation *SyscallInvocation   `protobuf:"bytes,3,opt,name=syscall_invocation,json=syscallInvocation,proto3" json:"syscall_invocation,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SyscallContext) Reset() {
	*x = SyscallContext{}
	mi := &file_vm_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyscallContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyscallContext) ProtoMessage() {}

func (x *SyscallContext) ProtoReflect() protoreflect.Message {
	mi := &file_vm_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyscallContext.ProtoReflect.Descriptor instead.
func (*SyscallContext) Descriptor() ([]byte, []int) {
	return file_vm_proto_rawDescGZIP(), []int{3}
}

func (x *SyscallContext) GetVmCtx() *VmContext {
	if x != nil {
		return x.VmCtx
	}
	return nil
}

func (x *SyscallContext) GetInstrCtx() *invoke.InstrContext {
	if x != nil {
		return x.InstrCtx
	}
	return nil
}

func (x *SyscallContext) GetSyscallInvocation() *SyscallInvocation {
	if x != nil {
		return x.SyscallInvocation
	}
	return nil
}

// The effects of executing a SyscallContext.
type SyscallEffects struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// EBPF error code, if the invocation was unsuccessful
	Error int64 `protobuf:"varint,1,opt,name=error,proto3" json:"error,omitempty"`
	// Error Kind (should be used along with error code)
	ErrorKind ErrKind `protobuf:"varint,12,opt,name=error_kind,json=errorKind,proto3,enum=org.solana.sealevel.v1.ErrKind" json:"error_kind,omitempty"`
	// Registers
	R0 uint64 `protobuf:"varint,2,opt,name=r0,proto3" json:"r0,omitempty"` // Result of a successful execution
	// CU's remaining
	CuAvail uint64 `protobuf:"varint,3,opt,name=cu_avail,json=cuAvail,proto3" json:"cu_avail,omitempty"`
	// Memory regions
	Heap             []byte             `protobuf:"bytes,4,opt,name=heap,proto3" json:"heap,omitempty"`
	Stack            []byte             `protobuf:"bytes,5,opt,name=stack,proto3" json:"stack,omitempty"`
	Inputdata        []byte             `protobuf:"bytes,6,opt,name=inputdata,proto3" json:"inputdata,omitempty"` // deprecated, use input_data_regions
	InputDataRegions []*InputDataRegion `protobuf:"bytes,11,rep,name=input_data_regions,json=inputDataRegions,proto3" json:"input_data_regions,omitempty"`
	// Current number of stack frames pushed
	FrameCount uint64 `protobuf:"varint,7,opt,name=frame_count,json=frameCount,proto3" json:"frame_count,omitempty"`
	// Syscall log
	Log    []byte `protobuf:"bytes,8,opt,name=log,proto3" json:"log,omitempty"`
	Rodata []byte `protobuf:"bytes,9,opt,name=rodata,proto3" json:"rodata,omitempty"`
	// VM state
	Pc uint64 `protobuf:"varint,10,opt,name=pc,proto3" json:"pc,omitempty"`
	// Output registers (to test interpreter)
	R1            uint64 `protobuf:"varint,107,opt,name=r1,proto3" json:"r1,omitempty"`
	R2            uint64 `protobuf:"varint,108,opt,name=r2,proto3" json:"r2,omitempty"`
	R3            uint64 `protobuf:"varint,109,opt,name=r3,proto3" json:"r3,omitempty"`
	R4            uint64 `protobuf:"varint,110,opt,name=r4,proto3" json:"r4,omitempty"`
	R5            uint64 `protobuf:"varint,111,opt,name=r5,proto3" json:"r5,omitempty"`
	R6            uint64 `protobuf:"varint,112,opt,name=r6,proto3" json:"r6,omitempty"`
	R7            uint64 `protobuf:"varint,113,opt,name=r7,proto3" json:"r7,omitempty"`
	R8            uint64 `protobuf:"varint,114,opt,name=r8,proto3" json:"r8,omitempty"`
	R9            uint64 `protobuf:"varint,115,opt,name=r9,proto3" json:"r9,omitempty"`
	R10           uint64 `protobuf:"varint,116,opt,name=r10,proto3" json:"r10,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyscallEffects) Reset() {
	*x = SyscallEffects{}
	mi := &file_vm_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyscallEffects) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyscallEffects) ProtoMessage() {}

func (x *SyscallEffects) ProtoReflect() protoreflect.Message {
	mi := &file_vm_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyscallEffects.ProtoReflect.Descriptor instead.
func (*SyscallEffects) Descriptor() ([]byte, []int) {
	return file_vm_proto_rawDescGZIP(), []int{4}
}

func (x *SyscallEffects) GetError() int64 {
	if x != nil {
		return x.Error
	}
	return 0
}

func (x *SyscallEffects) GetErrorKind() ErrKind {
	if x != nil {
		return x.ErrorKind
	}
	return ErrKind_UNSPECIFIED
}

func (x *SyscallEffects) GetR0() uint64 {
	if x != nil {
		return x.R0
	}
	return 0
}

func (x *SyscallEffects) GetCuAvail() uint64 {
	if x != nil {
		return x.CuAvail
	}
	return 0
}

func (x *SyscallEffects) GetHeap() []byte {
	if x != nil {
		return x.Heap
	}
	return nil
}

func (x *SyscallEffects) GetStack() []byte {
	if x != nil {
		return x.Stack
	}
	return nil
}

func (x *SyscallEffects) GetInputdata() []byte {
	if x != nil {
		return x.Inputdata
	}
	return nil
}

func (x *SyscallEffects) GetInputDataRegions() []*InputDataRegion {
	if x != nil {
		return x.InputDataRegions
	}
	return nil
}

func (x *SyscallEffects) GetFrameCount() uint64 {
	if x != nil {
		return x.FrameCount
	}
	return 0
}

func (x *SyscallEffects) GetLog() []byte {
	if x != nil {
		return x.Log
	}
	return nil
}

func (x *SyscallEffects) GetRodata() []byte {
	if x != nil {
		return x.Rodata
	}
	return nil
}

func (x *SyscallEffects) GetPc() uint64 {
	if x != nil {
		return x.Pc
	}
	return 0
}

func (x *SyscallEffects) GetR1() uint64 {
	if x != nil {
		return x.R1
	}
	return 0
}

func (x *SyscallEffects) GetR2() uint64 {
	if x != nil {
		return x.R2
	}
	return 0
}

func (x *SyscallEffects) GetR3() uint64 {
	if x != nil {
		return x.R3
	}
	return 0
}

func (x *SyscallEffects) GetR4() uint64 {
	if x != nil {
		return x.R4
	}
	return 0
}

func (x *SyscallEffects) GetR5() uint64 {
	if x != nil {
		return x.R5
	}
	return 0
}

func (x *SyscallEffects) GetR6() uint64 {
	if x != nil {
		return x.R6
	}
	return 0
}

func (x *SyscallEffects) GetR7() uint64 {
	if x != nil {
		return x.R7
	}
	return 0
}

func (x *SyscallEffects) GetR8() uint64 {
	if x != nil {
		return x.R8
	}
	return 0
}

func (x *SyscallEffects) GetR9() uint64 {
	if x != nil {
		return x.R9
	}
	return 0
}

func (x *SyscallEffects) GetR10() uint64 {
	if x != nil {
		return x.R10
	}
	return 0
}

// A syscall processing test fixture.
type SyscallFixture struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Metadata      *metadata.FixtureMetadata `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Input         *SyscallContext           `protobuf:"bytes,2,opt,name=input,proto3" json:"input,omitempty"`
	Output        *SyscallEffects           `protobuf:"bytes,3,opt,name=output,proto3" json:"output,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyscallFixture) Reset() {
	*x = SyscallFixture{}
	mi := &file_vm_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyscallFixture) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyscallFixture) ProtoMessage() {}

func (x *SyscallFixture) ProtoReflect() protoreflect.Message {
	mi := &file_vm_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyscallFixture.ProtoReflect.Descriptor instead.
func (*SyscallFixture) Descriptor() ([]byte, []int) {
	return file_vm_proto_rawDescGZIP(), []int{5}
}

func (x *SyscallFixture) GetMetadata() *metadata.FixtureMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *SyscallFixture) GetInput() *SyscallContext {
	if x != nil {
		return x.Input
	}
	return nil
}

func (x *SyscallFixture) GetOutput() *SyscallEffects {
	if x != nil {
		return x.Output
	}
	return nil
}

// Everything needed to setup a fd_vm_t
type FullVmContext struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	VmCtx *VmContext             `protobuf:"bytes,1,opt,name=vm_ctx,json=vmCtx,proto3" json:"vm_ctx,omitempty"`
	// InstrContext instr_ctx = 2;
	Features      *context.FeatureSet `protobuf:"bytes,3,opt,name=features,proto3" json:"features,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FullVmContext) Reset() {
	*x = FullVmContext{}
	mi := &file_vm_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FullVmContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FullVmContext) ProtoMessage() {}

func (x *FullVmContext) ProtoReflect() protoreflect.Message {
	mi := &file_vm_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FullVmContext.ProtoReflect.Descriptor instead.
func (*FullVmContext) Descriptor() ([]byte, []int) {
	return file_vm_proto_rawDescGZIP(), []int{6}
}

func (x *FullVmContext) GetVmCtx() *VmContext {
	if x != nil {
		return x.VmCtx
	}
	return nil
}

func (x *FullVmContext) GetFeatures() *context.FeatureSet {
	if x != nil {
		return x.Features
	}
	return nil
}

// Effects of fd_vm_validate
type ValidateVmEffects struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Result int32                  `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	// if result is 0 (success), protobuf will be empty!!
	Success       bool `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateVmEffects) Reset() {
	*x = ValidateVmEffects{}
	mi := &file_vm_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateVmEffects) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateVmEffects) ProtoMessage() {}

func (x *ValidateVmEffects) ProtoReflect() protoreflect.Message {
	mi := &file_vm_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateVmEffects.ProtoReflect.Descriptor instead.
func (*ValidateVmEffects) Descriptor() ([]byte, []int) {
	return file_vm_proto_rawDescGZIP(), []int{7}
}

func (x *ValidateVmEffects) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

func (x *ValidateVmEffects) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// Fixture for fd_vm_validate fuzz harness
type ValidateVmFixture struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Metadata      *metadata.FixtureMetadata `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Input         *FullVmContext            `protobuf:"bytes,2,opt,name=input,proto3" json:"input,omitempty"`
	Output        *ValidateVmEffects        `protobuf:"bytes,3,opt,name=output,proto3" json:"output,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateVmFixture) Reset() {
	*x = ValidateVmFixture{}
	mi := &file_vm_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateVmFixture) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateVmFixture) ProtoMessage() {}

func (x *ValidateVmFixture) ProtoReflect() protoreflect.Message {
	mi := &file_vm_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateVmFixture.ProtoReflect.Descriptor instead.
func (*ValidateVmFixture) Descriptor() ([]byte, []int) {
	return file_vm_proto_rawDescGZIP(), []int{8}
}

func (x *ValidateVmFixture) GetMetadata() *metadata.FixtureMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *ValidateVmFixture) GetInput() *FullVmContext {
	if x != nil {
		return x.Input
	}
	return nil
}

func (x *ValidateVmFixture) GetOutput() *ValidateVmEffects {
	if x != nil {
		return x.Output
	}
	return nil
}

type ReturnData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProgramId     []byte                 `protobuf:"bytes,1,opt,name=program_id,json=programId,proto3" json:"program_id,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReturnData) Reset() {
	*x = ReturnData{}
	mi := &file_vm_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReturnData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReturnData) ProtoMessage() {}

func (x *ReturnData) ProtoReflect() protoreflect.Message {
	mi := &file_vm_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReturnData.ProtoReflect.Descriptor instead.
func (*ReturnData) Descriptor() ([]byte, []int) {
	return file_vm_proto_rawDescGZIP(), []int{9}
}

func (x *ReturnData) GetProgramId() []byte {
	if x != nil {
		return x.ProgramId
	}
	return nil
}

func (x *ReturnData) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_vm_proto protoreflect.FileDescriptor

const file_vm_proto_rawDesc = "" +
	"\n" +
	"\bvm.proto\x12\x16org.solana.sealevel.v1\x1a\finvoke.proto\x1a\rcontext.proto\x1a\x0emetadata.proto\"d\n" +
	"\x0fInputDataRegion\x12\x16\n" +
	"\x06offset\x18\x01 \x01(\x04R\x06offset\x12\x18\n" +
	"\acontent\x18\x02 \x01(\fR\acontent\x12\x1f\n" +
	"\vis_writable\x18\x03 \x01(\bR\n" +
	"isWritable\"\xcf\x04\n" +
	"\tVmContext\x12\x19\n" +
	"\bheap_max\x18\x01 \x01(\x04R\aheapMax\x12\x16\n" +
	"\x06rodata\x18\x02 \x01(\fR\x06rodata\x12;\n" +
	"\x1arodata_text_section_offset\x18\x03 \x01(\x04R\x17rodataTextSectionOffset\x12;\n" +
	"\x1arodata_text_section_length\x18\x04 \x01(\x04R\x17rodataTextSectionLength\x12\x0e\n" +
	"\x02r0\x18\x06 \x01(\x04R\x02r0\x12\x0e\n" +
	"\x02r1\x18\a \x01(\x04R\x02r1\x12\x0e\n" +
	"\x02r2\x18\b \x01(\x04R\x02r2\x12\x0e\n" +
	"\x02r3\x18\t \x01(\x04R\x02r3\x12\x0e\n" +
	"\x02r4\x18\n" +
	" \x01(\x04R\x02r4\x12\x0e\n" +
	"\x02r5\x18\v \x01(\x04R\x02r5\x12\x0e\n" +
	"\x02r6\x18\f \x01(\x04R\x02r6\x12\x0e\n" +
	"\x02r7\x18\r \x01(\x04R\x02r7\x12\x0e\n" +
	"\x02r8\x18\x0e \x01(\x04R\x02r8\x12\x0e\n" +
	"\x02r9\x18\x0f \x01(\x04R\x02r9\x12\x10\n" +
	"\x03r10\x18\x10 \x01(\x04R\x03r10\x12\x10\n" +
	"\x03r11\x18\x11 \x01(\x04R\x03r11\x12\x19\n" +
	"\bentry_pc\x18\x14 \x01(\x04R\aentryPc\x12%\n" +
	"\x0ecall_whitelist\x18\x15 \x01(\fR\rcallWhitelist\x12'\n" +
	"\x0ftracing_enabled\x18\x16 \x01(\bR\x0etracingEnabled\x12C\n" +
	"\vreturn_data\x18\x17 \x01(\v2\".org.solana.sealevel.v1.ReturnDataR\n" +
	"returnData\x12!\n" +
	"\fsbpf_version\x18\x18 \x01(\rR\vsbpfVersion\"|\n" +
	"\x11SyscallInvocation\x12#\n" +
	"\rfunction_name\x18\x01 \x01(\fR\ffunctionName\x12\x1f\n" +
	"\vheap_prefix\x18\x02 \x01(\fR\n" +
	"heapPrefix\x12!\n" +
	"\fstack_prefix\x18\x03 \x01(\fR\vstackPrefix\"\xe7\x01\n" +
	"\x0eSyscallContext\x128\n" +
	"\x06vm_ctx\x18\x01 \x01(\v2!.org.solana.sealevel.v1.VmContextR\x05vmCtx\x12A\n" +
	"\tinstr_ctx\x18\x02 \x01(\v2$.org.solana.sealevel.v1.InstrContextR\binstrCtx\x12X\n" +
	"\x12syscall_invocation\x18\x03 \x01(\v2).org.solana.sealevel.v1.SyscallInvocationR\x11syscallInvocation\"\xad\x04\n" +
	"\x0eSyscallEffects\x12\x14\n" +
	"\x05error\x18\x01 \x01(\x03R\x05error\x12>\n" +
	"\n" +
	"error_kind\x18\f \x01(\x0e2\x1f.org.solana.sealevel.v1.ErrKindR\terrorKind\x12\x0e\n" +
	"\x02r0\x18\x02 \x01(\x04R\x02r0\x12\x19\n" +
	"\bcu_avail\x18\x03 \x01(\x04R\acuAvail\x12\x12\n" +
	"\x04heap\x18\x04 \x01(\fR\x04heap\x12\x14\n" +
	"\x05stack\x18\x05 \x01(\fR\x05stack\x12\x1c\n" +
	"\tinputdata\x18\x06 \x01(\fR\tinputdata\x12U\n" +
	"\x12input_data_regions\x18\v \x03(\v2'.org.solana.sealevel.v1.InputDataRegionR\x10inputDataRegions\x12\x1f\n" +
	"\vframe_count\x18\a \x01(\x04R\n" +
	"frameCount\x12\x10\n" +
	"\x03log\x18\b \x01(\fR\x03log\x12\x16\n" +
	"\x06rodata\x18\t \x01(\fR\x06rodata\x12\x0e\n" +
	"\x02pc\x18\n" +
	" \x01(\x04R\x02pc\x12\x0e\n" +
	"\x02r1\x18k \x01(\x04R\x02r1\x12\x0e\n" +
	"\x02r2\x18l \x01(\x04R\x02r2\x12\x0e\n" +
	"\x02r3\x18m \x01(\x04R\x02r3\x12\x0e\n" +
	"\x02r4\x18n \x01(\x04R\x02r4\x12\x0e\n" +
	"\x02r5\x18o \x01(\x04R\x02r5\x12\x0e\n" +
	"\x02r6\x18p \x01(\x04R\x02r6\x12\x0e\n" +
	"\x02r7\x18q \x01(\x04R\x02r7\x12\x0e\n" +
	"\x02r8\x18r \x01(\x04R\x02r8\x12\x0e\n" +
	"\x02r9\x18s \x01(\x04R\x02r9\x12\x10\n" +
	"\x03r10\x18t \x01(\x04R\x03r10\"\xd3\x01\n" +
	"\x0eSyscallFixture\x12C\n" +
	"\bmetadata\x18\x01 \x01(\v2'.org.solana.sealevel.v1.FixtureMetadataR\bmetadata\x12<\n" +
	"\x05input\x18\x02 \x01(\v2&.org.solana.sealevel.v1.SyscallContextR\x05input\x12>\n" +
	"\x06output\x18\x03 \x01(\v2&.org.solana.sealevel.v1.SyscallEffectsR\x06output\"\x89\x01\n" +
	"\rFullVmContext\x128\n" +
	"\x06vm_ctx\x18\x01 \x01(\v2!.org.solana.sealevel.v1.VmContextR\x05vmCtx\x12>\n" +
	"\bfeatures\x18\x03 \x01(\v2\".org.solana.sealevel.v1.FeatureSetR\bfeatures\"E\n" +
	"\x11ValidateVmEffects\x12\x16\n" +
	"\x06result\x18\x01 \x01(\x05R\x06result\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\"\xd8\x01\n" +
	"\x11ValidateVmFixture\x12C\n" +
	"\bmetadata\x18\x01 \x01(\v2'.org.solana.sealevel.v1.FixtureMetadataR\bmetadata\x12;\n" +
	"\x05input\x18\x02 \x01(\v2%.org.solana.sealevel.v1.FullVmContextR\x05input\x12A\n" +
	"\x06output\x18\x03 \x01(\v2).org.solana.sealevel.v1.ValidateVmEffectsR\x06output\"?\n" +
	"\n" +
	"ReturnData\x12\x1d\n" +
	"\n" +
	"program_id\x18\x01 \x01(\fR\tprogramId\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data*B\n" +
	"\aErrKind\x12\x0f\n" +
	"\vUNSPECIFIED\x10\x00\x12\b\n" +
	"\x04EBPF\x10\x01\x12\v\n" +
	"\aSYSCALL\x10\x02\x12\x0f\n" +
	"\vINSTRUCTION\x10\x03b\x06proto3"

var (
	file_vm_proto_rawDescOnce sync.Once
	file_vm_proto_rawDescData []byte
)

func file_vm_proto_rawDescGZIP() []byte {
	file_vm_proto_rawDescOnce.Do(func() {
		file_vm_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_vm_proto_rawDesc), len(file_vm_proto_rawDesc)))
	})
	return file_vm_proto_rawDescData
}

var file_vm_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_vm_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_vm_proto_goTypes = []any{
	(ErrKind)(0),                     // 0: org.solana.sealevel.v1.ErrKind
	(*InputDataRegion)(nil),          // 1: org.solana.sealevel.v1.InputDataRegion
	(*VmContext)(nil),                // 2: org.solana.sealevel.v1.VmContext
	(*SyscallInvocation)(nil),        // 3: org.solana.sealevel.v1.SyscallInvocation
	(*SyscallContext)(nil),           // 4: org.solana.sealevel.v1.SyscallContext
	(*SyscallEffects)(nil),           // 5: org.solana.sealevel.v1.SyscallEffects
	(*SyscallFixture)(nil),           // 6: org.solana.sealevel.v1.SyscallFixture
	(*FullVmContext)(nil),            // 7: org.solana.sealevel.v1.FullVmContext
	(*ValidateVmEffects)(nil),        // 8: org.solana.sealevel.v1.ValidateVmEffects
	(*ValidateVmFixture)(nil),        // 9: org.solana.sealevel.v1.ValidateVmFixture
	(*ReturnData)(nil),               // 10: org.solana.sealevel.v1.ReturnData
	(*invoke.InstrContext)(nil),      // 11: org.solana.sealevel.v1.InstrContext
	(*metadata.FixtureMetadata)(nil), // 12: org.solana.sealevel.v1.FixtureMetadata
	(*context.FeatureSet)(nil),       // 13: org.solana.sealevel.v1.FeatureSet
}
var file_vm_proto_depIdxs = []int32{
	10, // 0: org.solana.sealevel.v1.VmContext.return_data:type_name -> org.solana.sealevel.v1.ReturnData
	2,  // 1: org.solana.sealevel.v1.SyscallContext.vm_ctx:type_name -> org.solana.sealevel.v1.VmContext
	11, // 2: org.solana.sealevel.v1.SyscallContext.instr_ctx:type_name -> org.solana.sealevel.v1.InstrContext
	3,  // 3: org.solana.sealevel.v1.SyscallContext.syscall_invocation:type_name -> org.solana.sealevel.v1.SyscallInvocation
	0,  // 4: org.solana.sealevel.v1.SyscallEffects.error_kind:type_name -> org.solana.sealevel.v1.ErrKind
	1,  // 5: org.solana.sealevel.v1.SyscallEffects.input_data_regions:type_name -> org.solana.sealevel.v1.InputDataRegion
	12, // 6: org.solana.sealevel.v1.SyscallFixture.metadata:type_name -> org.solana.sealevel.v1.FixtureMetadata
	4,  // 7: org.solana.sealevel.v1.SyscallFixture.input:type_name -> org.solana.sealevel.v1.SyscallContext
	5,  // 8: org.solana.sealevel.v1.SyscallFixture.output:type_name -> org.solana.sealevel.v1.SyscallEffects
	2,  // 9: org.solana.sealevel.v1.FullVmContext.vm_ctx:type_name -> org.solana.sealevel.v1.VmContext
	13, // 10: org.solana.sealevel.v1.FullVmContext.features:type_name -> org.solana.sealevel.v1.FeatureSet
	12, // 11: org.solana.sealevel.v1.ValidateVmFixture.metadata:type_name -> org.solana.sealevel.v1.FixtureMetadata
	7,  // 12: org.solana.sealevel.v1.ValidateVmFixture.input:type_name -> org.solana.sealevel.v1.FullVmContext
	8,  // 13: org.solana.sealevel.v1.ValidateVmFixture.output:type_name -> org.solana.sealevel.v1.ValidateVmEffects
	14, // [14:14] is the sub-list for method output_type
	14, // [14:14] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_vm_proto_init() }
func file_vm_proto_init() {
	if File_vm_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_vm_proto_rawDesc), len(file_vm_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_vm_proto_goTypes,
		DependencyIndexes: file_vm_proto_depIdxs,
		EnumInfos:         file_vm_proto_enumTypes,
		MessageInfos:      file_vm_proto_msgTypes,
	}.Build()
	File_vm_proto = out.File
	file_vm_proto_goTypes = nil
	file_vm_proto_depIdxs = nil
}
