// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: type.proto

package _type

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	metadata "github.com/Overclock-Validator/mithril/pkg/protosol-go/metadata"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TypeContext struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       []byte                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	Typename      string                 `protobuf:"bytes,2,opt,name=typename,proto3" json:"typename,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TypeContext) Reset() {
	*x = TypeContext{}
	mi := &file_type_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TypeContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TypeContext) ProtoMessage() {}

func (x *TypeContext) ProtoReflect() protoreflect.Message {
	mi := &file_type_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TypeContext.ProtoReflect.Descriptor instead.
func (*TypeContext) Descriptor() ([]byte, []int) {
	return file_type_proto_rawDescGZIP(), []int{0}
}

func (x *TypeContext) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *TypeContext) GetTypename() string {
	if x != nil {
		return x.Typename
	}
	return ""
}

type TypeEffects struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Result         uint64                 `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	Representation []byte                 `protobuf:"bytes,2,opt,name=representation,proto3" json:"representation,omitempty"`
	Yaml           []byte                 `protobuf:"bytes,3,opt,name=yaml,proto3" json:"yaml,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TypeEffects) Reset() {
	*x = TypeEffects{}
	mi := &file_type_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TypeEffects) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TypeEffects) ProtoMessage() {}

func (x *TypeEffects) ProtoReflect() protoreflect.Message {
	mi := &file_type_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TypeEffects.ProtoReflect.Descriptor instead.
func (*TypeEffects) Descriptor() ([]byte, []int) {
	return file_type_proto_rawDescGZIP(), []int{1}
}

func (x *TypeEffects) GetResult() uint64 {
	if x != nil {
		return x.Result
	}
	return 0
}

func (x *TypeEffects) GetRepresentation() []byte {
	if x != nil {
		return x.Representation
	}
	return nil
}

func (x *TypeEffects) GetYaml() []byte {
	if x != nil {
		return x.Yaml
	}
	return nil
}

type TypeFixture struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Metadata      *metadata.FixtureMetadata `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Input         *TypeContext              `protobuf:"bytes,2,opt,name=input,proto3" json:"input,omitempty"`
	Output        *TypeEffects              `protobuf:"bytes,3,opt,name=output,proto3" json:"output,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TypeFixture) Reset() {
	*x = TypeFixture{}
	mi := &file_type_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TypeFixture) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TypeFixture) ProtoMessage() {}

func (x *TypeFixture) ProtoReflect() protoreflect.Message {
	mi := &file_type_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TypeFixture.ProtoReflect.Descriptor instead.
func (*TypeFixture) Descriptor() ([]byte, []int) {
	return file_type_proto_rawDescGZIP(), []int{2}
}

func (x *TypeFixture) GetMetadata() *metadata.FixtureMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *TypeFixture) GetInput() *TypeContext {
	if x != nil {
		return x.Input
	}
	return nil
}

func (x *TypeFixture) GetOutput() *TypeEffects {
	if x != nil {
		return x.Output
	}
	return nil
}

var File_type_proto protoreflect.FileDescriptor

const file_type_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"type.proto\x12\x16org.solana.sealevel.v1\x1a\x0emetadata.proto\"C\n" +
	"\vTypeContext\x12\x18\n" +
	"\acontent\x18\x01 \x01(\fR\acontent\x12\x1a\n" +
	"\btypename\x18\x02 \x01(\tR\btypename\"a\n" +
	"\vTypeEffects\x12\x16\n" +
	"\x06result\x18\x01 \x01(\x04R\x06result\x12&\n" +
	"\x0erepresentation\x18\x02 \x01(\fR\x0erepresentation\x12\x12\n" +
	"\x04yaml\x18\x03 \x01(\fR\x04yaml\"\xca\x01\n" +
	"\vTypeFixture\x12C\n" +
	"\bmetadata\x18\x01 \x01(\v2'.org.solana.sealevel.v1.FixtureMetadataR\bmetadata\x129\n" +
	"\x05input\x18\x02 \x01(\v2#.org.solana.sealevel.v1.TypeContextR\x05input\x12;\n" +
	"\x06output\x18\x03 \x01(\v2#.org.solana.sealevel.v1.TypeEffectsR\x06outputb\x06proto3"

var (
	file_type_proto_rawDescOnce sync.Once
	file_type_proto_rawDescData []byte
)

func file_type_proto_rawDescGZIP() []byte {
	file_type_proto_rawDescOnce.Do(func() {
		file_type_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_type_proto_rawDesc), len(file_type_proto_rawDesc)))
	})
	return file_type_proto_rawDescData
}

var file_type_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_type_proto_goTypes = []any{
	(*TypeContext)(nil),              // 0: org.solana.sealevel.v1.TypeContext
	(*TypeEffects)(nil),              // 1: org.solana.sealevel.v1.TypeEffects
	(*TypeFixture)(nil),              // 2: org.solana.sealevel.v1.TypeFixture
	(*metadata.FixtureMetadata)(nil), // 3: org.solana.sealevel.v1.FixtureMetadata
}
var file_type_proto_depIdxs = []int32{
	3, // 0: org.solana.sealevel.v1.TypeFixture.metadata:type_name -> org.solana.sealevel.v1.FixtureMetadata
	0, // 1: org.solana.sealevel.v1.TypeFixture.input:type_name -> org.solana.sealevel.v1.TypeContext
	1, // 2: org.solana.sealevel.v1.TypeFixture.output:type_name -> org.solana.sealevel.v1.TypeEffects
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_type_proto_init() }
func file_type_proto_init() {
	if File_type_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_type_proto_rawDesc), len(file_type_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_type_proto_goTypes,
		DependencyIndexes: file_type_proto_depIdxs,
		MessageInfos:      file_type_proto_msgTypes,
	}.Build()
	File_type_proto = out.File
	file_type_proto_goTypes = nil
	file_type_proto_depIdxs = nil
}
