// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: context.proto

package context

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// A set of feature flags.
type FeatureSet struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Every item in this list marks an enabled feature.  The value of
	// each item is the first 8 bytes of the feature ID as a little-
	// endian integer.
	Features      []uint64 `protobuf:"fixed64,1,rep,packed,name=features,proto3" json:"features,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FeatureSet) Reset() {
	*x = FeatureSet{}
	mi := &file_context_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeatureSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeatureSet) ProtoMessage() {}

func (x *FeatureSet) ProtoReflect() protoreflect.Message {
	mi := &file_context_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeatureSet.ProtoReflect.Descriptor instead.
func (*FeatureSet) Descriptor() ([]byte, []int) {
	return file_context_proto_rawDescGZIP(), []int{0}
}

func (x *FeatureSet) GetFeatures() []uint64 {
	if x != nil {
		return x.Features
	}
	return nil
}

// The complete state of an account excluding its public key.
type AcctState struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The account address.  (32 bytes)
	Address  []byte `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Lamports uint64 `protobuf:"varint,2,opt,name=lamports,proto3" json:"lamports,omitempty"`
	// Account data is limited to 10 MiB on Solana mainnet as of 2024-Feb.
	Data       []byte `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	Executable bool   `protobuf:"varint,4,opt,name=executable,proto3" json:"executable,omitempty"`
	// Address of the program that owns this account.  (32 bytes)
	Owner         []byte `protobuf:"bytes,6,opt,name=owner,proto3" json:"owner,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcctState) Reset() {
	*x = AcctState{}
	mi := &file_context_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcctState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcctState) ProtoMessage() {}

func (x *AcctState) ProtoReflect() protoreflect.Message {
	mi := &file_context_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcctState.ProtoReflect.Descriptor instead.
func (*AcctState) Descriptor() ([]byte, []int) {
	return file_context_proto_rawDescGZIP(), []int{1}
}

func (x *AcctState) GetAddress() []byte {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *AcctState) GetLamports() uint64 {
	if x != nil {
		return x.Lamports
	}
	return 0
}

func (x *AcctState) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *AcctState) GetExecutable() bool {
	if x != nil {
		return x.Executable
	}
	return false
}

func (x *AcctState) GetOwner() []byte {
	if x != nil {
		return x.Owner
	}
	return nil
}

type VoteAccount struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Account state of the vote account
	VoteAccount *AcctState `protobuf:"bytes,1,opt,name=vote_account,json=voteAccount,proto3" json:"vote_account,omitempty"`
	// How much stake has been delegated to this account
	Stake         uint64 `protobuf:"varint,2,opt,name=stake,proto3" json:"stake,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VoteAccount) Reset() {
	*x = VoteAccount{}
	mi := &file_context_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VoteAccount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VoteAccount) ProtoMessage() {}

func (x *VoteAccount) ProtoReflect() protoreflect.Message {
	mi := &file_context_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VoteAccount.ProtoReflect.Descriptor instead.
func (*VoteAccount) Descriptor() ([]byte, []int) {
	return file_context_proto_rawDescGZIP(), []int{2}
}

func (x *VoteAccount) GetVoteAccount() *AcctState {
	if x != nil {
		return x.VoteAccount
	}
	return nil
}

func (x *VoteAccount) GetStake() uint64 {
	if x != nil {
		return x.Stake
	}
	return 0
}

// Epoch bank inflation parameters
type Inflation struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Initial        float64                `protobuf:"fixed64,1,opt,name=initial,proto3" json:"initial,omitempty"`
	Terminal       float64                `protobuf:"fixed64,2,opt,name=terminal,proto3" json:"terminal,omitempty"`
	Taper          float64                `protobuf:"fixed64,3,opt,name=taper,proto3" json:"taper,omitempty"`
	Foundation     float64                `protobuf:"fixed64,4,opt,name=foundation,proto3" json:"foundation,omitempty"`
	FoundationTerm float64                `protobuf:"fixed64,5,opt,name=foundation_term,json=foundationTerm,proto3" json:"foundation_term,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Inflation) Reset() {
	*x = Inflation{}
	mi := &file_context_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Inflation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Inflation) ProtoMessage() {}

func (x *Inflation) ProtoReflect() protoreflect.Message {
	mi := &file_context_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Inflation.ProtoReflect.Descriptor instead.
func (*Inflation) Descriptor() ([]byte, []int) {
	return file_context_proto_rawDescGZIP(), []int{3}
}

func (x *Inflation) GetInitial() float64 {
	if x != nil {
		return x.Initial
	}
	return 0
}

func (x *Inflation) GetTerminal() float64 {
	if x != nil {
		return x.Terminal
	}
	return 0
}

func (x *Inflation) GetTaper() float64 {
	if x != nil {
		return x.Taper
	}
	return 0
}

func (x *Inflation) GetFoundation() float64 {
	if x != nil {
		return x.Foundation
	}
	return 0
}

func (x *Inflation) GetFoundationTerm() float64 {
	if x != nil {
		return x.FoundationTerm
	}
	return 0
}

// Fee rate governor parameters
type FeeRateGovernor struct {
	state                      protoimpl.MessageState `protogen:"open.v1"`
	TargetLamportsPerSignature uint64                 `protobuf:"varint,1,opt,name=target_lamports_per_signature,json=targetLamportsPerSignature,proto3" json:"target_lamports_per_signature,omitempty"`
	TargetSignaturesPerSlot    uint64                 `protobuf:"varint,2,opt,name=target_signatures_per_slot,json=targetSignaturesPerSlot,proto3" json:"target_signatures_per_slot,omitempty"`
	MinLamportsPerSignature    uint64                 `protobuf:"varint,3,opt,name=min_lamports_per_signature,json=minLamportsPerSignature,proto3" json:"min_lamports_per_signature,omitempty"`
	MaxLamportsPerSignature    uint64                 `protobuf:"varint,4,opt,name=max_lamports_per_signature,json=maxLamportsPerSignature,proto3" json:"max_lamports_per_signature,omitempty"`
	BurnPercent                uint32                 `protobuf:"varint,5,opt,name=burn_percent,json=burnPercent,proto3" json:"burn_percent,omitempty"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *FeeRateGovernor) Reset() {
	*x = FeeRateGovernor{}
	mi := &file_context_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeeRateGovernor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeeRateGovernor) ProtoMessage() {}

func (x *FeeRateGovernor) ProtoReflect() protoreflect.Message {
	mi := &file_context_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeeRateGovernor.ProtoReflect.Descriptor instead.
func (*FeeRateGovernor) Descriptor() ([]byte, []int) {
	return file_context_proto_rawDescGZIP(), []int{4}
}

func (x *FeeRateGovernor) GetTargetLamportsPerSignature() uint64 {
	if x != nil {
		return x.TargetLamportsPerSignature
	}
	return 0
}

func (x *FeeRateGovernor) GetTargetSignaturesPerSlot() uint64 {
	if x != nil {
		return x.TargetSignaturesPerSlot
	}
	return 0
}

func (x *FeeRateGovernor) GetMinLamportsPerSignature() uint64 {
	if x != nil {
		return x.MinLamportsPerSignature
	}
	return 0
}

func (x *FeeRateGovernor) GetMaxLamportsPerSignature() uint64 {
	if x != nil {
		return x.MaxLamportsPerSignature
	}
	return 0
}

func (x *FeeRateGovernor) GetBurnPercent() uint32 {
	if x != nil {
		return x.BurnPercent
	}
	return 0
}

// EpochContext includes context scoped to an epoch.
// On "real" ledgers, it is created during the epoch boundary.
type EpochContext struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Active feature set
	Features *FeatureSet `protobuf:"bytes,1,opt,name=features,proto3" json:"features,omitempty"`
	// Hashes per tick
	HashesPerTick uint64 `protobuf:"varint,2,opt,name=hashes_per_tick,json=hashesPerTick,proto3" json:"hashes_per_tick,omitempty"`
	// Ticks per slot
	TicksPerSlot uint64 `protobuf:"varint,3,opt,name=ticks_per_slot,json=ticksPerSlot,proto3" json:"ticks_per_slot,omitempty"`
	// Slots per year
	SlotsPerYear float64 `protobuf:"fixed64,4,opt,name=slots_per_year,json=slotsPerYear,proto3" json:"slots_per_year,omitempty"`
	// Inflation
	Inflation *Inflation `protobuf:"bytes,5,opt,name=inflation,proto3" json:"inflation,omitempty"`
	// Genesis creation time
	GenesisCreationTime uint64 `protobuf:"varint,6,opt,name=genesis_creation_time,json=genesisCreationTime,proto3" json:"genesis_creation_time,omitempty"`
	// Epoch vote accounts for epochs T-1 and T-2
	VoteAccountsT_1 []*VoteAccount `protobuf:"bytes,11,rep,name=vote_accounts_t_1,json=voteAccountsT1,proto3" json:"vote_accounts_t_1,omitempty"`
	VoteAccountsT_2 []*VoteAccount `protobuf:"bytes,12,rep,name=vote_accounts_t_2,json=voteAccountsT2,proto3" json:"vote_accounts_t_2,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *EpochContext) Reset() {
	*x = EpochContext{}
	mi := &file_context_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EpochContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EpochContext) ProtoMessage() {}

func (x *EpochContext) ProtoReflect() protoreflect.Message {
	mi := &file_context_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EpochContext.ProtoReflect.Descriptor instead.
func (*EpochContext) Descriptor() ([]byte, []int) {
	return file_context_proto_rawDescGZIP(), []int{5}
}

func (x *EpochContext) GetFeatures() *FeatureSet {
	if x != nil {
		return x.Features
	}
	return nil
}

func (x *EpochContext) GetHashesPerTick() uint64 {
	if x != nil {
		return x.HashesPerTick
	}
	return 0
}

func (x *EpochContext) GetTicksPerSlot() uint64 {
	if x != nil {
		return x.TicksPerSlot
	}
	return 0
}

func (x *EpochContext) GetSlotsPerYear() float64 {
	if x != nil {
		return x.SlotsPerYear
	}
	return 0
}

func (x *EpochContext) GetInflation() *Inflation {
	if x != nil {
		return x.Inflation
	}
	return nil
}

func (x *EpochContext) GetGenesisCreationTime() uint64 {
	if x != nil {
		return x.GenesisCreationTime
	}
	return 0
}

func (x *EpochContext) GetVoteAccountsT_1() []*VoteAccount {
	if x != nil {
		return x.VoteAccountsT_1
	}
	return nil
}

func (x *EpochContext) GetVoteAccountsT_2() []*VoteAccount {
	if x != nil {
		return x.VoteAccountsT_2
	}
	return nil
}

// SlotContext includes context scoped to a block.
// On "real" ledgers, it is created during the slot boundary.
type SlotContext struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Current slot number
	Slot        uint64 `protobuf:"fixed64,1,opt,name=slot,proto3" json:"slot,omitempty"`
	BlockHeight uint64 `protobuf:"fixed64,2,opt,name=block_height,json=blockHeight,proto3" json:"block_height,omitempty"`
	// POH hash
	Poh []byte `protobuf:"bytes,3,opt,name=poh,proto3" json:"poh,omitempty"`
	// Parent bank hash
	ParentBankHash []byte `protobuf:"bytes,4,opt,name=parent_bank_hash,json=parentBankHash,proto3" json:"parent_bank_hash,omitempty"`
	// Parent lt hash
	ParentLthash []byte `protobuf:"bytes,5,opt,name=parent_lthash,json=parentLthash,proto3" json:"parent_lthash,omitempty"`
	// The last executed slot
	PrevSlot uint64 `protobuf:"fixed64,6,opt,name=prev_slot,json=prevSlot,proto3" json:"prev_slot,omitempty"`
	// Last slot lamports per signature
	PrevLps uint64 `protobuf:"varint,7,opt,name=prev_lps,json=prevLps,proto3" json:"prev_lps,omitempty"`
	// Previous slot's capitalization.
	// TODO: I was very smart and named this incorrectly. This should be fixed in the future.
	PrevEpochCapitalization uint64 `protobuf:"varint,8,opt,name=prev_epoch_capitalization,json=prevEpochCapitalization,proto3" json:"prev_epoch_capitalization,omitempty"`
	// Fee rate governor
	FeeRateGovernor *FeeRateGovernor `protobuf:"bytes,9,opt,name=fee_rate_governor,json=feeRateGovernor,proto3" json:"fee_rate_governor,omitempty"`
	// Parent signature count (used for fee rate governor)
	ParentSignatureCount uint64 `protobuf:"varint,10,opt,name=parent_signature_count,json=parentSignatureCount,proto3" json:"parent_signature_count,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *SlotContext) Reset() {
	*x = SlotContext{}
	mi := &file_context_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SlotContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SlotContext) ProtoMessage() {}

func (x *SlotContext) ProtoReflect() protoreflect.Message {
	mi := &file_context_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SlotContext.ProtoReflect.Descriptor instead.
func (*SlotContext) Descriptor() ([]byte, []int) {
	return file_context_proto_rawDescGZIP(), []int{6}
}

func (x *SlotContext) GetSlot() uint64 {
	if x != nil {
		return x.Slot
	}
	return 0
}

func (x *SlotContext) GetBlockHeight() uint64 {
	if x != nil {
		return x.BlockHeight
	}
	return 0
}

func (x *SlotContext) GetPoh() []byte {
	if x != nil {
		return x.Poh
	}
	return nil
}

func (x *SlotContext) GetParentBankHash() []byte {
	if x != nil {
		return x.ParentBankHash
	}
	return nil
}

func (x *SlotContext) GetParentLthash() []byte {
	if x != nil {
		return x.ParentLthash
	}
	return nil
}

func (x *SlotContext) GetPrevSlot() uint64 {
	if x != nil {
		return x.PrevSlot
	}
	return 0
}

func (x *SlotContext) GetPrevLps() uint64 {
	if x != nil {
		return x.PrevLps
	}
	return 0
}

func (x *SlotContext) GetPrevEpochCapitalization() uint64 {
	if x != nil {
		return x.PrevEpochCapitalization
	}
	return 0
}

func (x *SlotContext) GetFeeRateGovernor() *FeeRateGovernor {
	if x != nil {
		return x.FeeRateGovernor
	}
	return nil
}

func (x *SlotContext) GetParentSignatureCount() uint64 {
	if x != nil {
		return x.ParentSignatureCount
	}
	return 0
}

var File_context_proto protoreflect.FileDescriptor

const file_context_proto_rawDesc = "" +
	"\n" +
	"\rcontext.proto\x12\x16org.solana.sealevel.v1\"(\n" +
	"\n" +
	"FeatureSet\x12\x1a\n" +
	"\bfeatures\x18\x01 \x03(\x06R\bfeatures\"\x97\x01\n" +
	"\tAcctState\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\fR\aaddress\x12\x1a\n" +
	"\blamports\x18\x02 \x01(\x04R\blamports\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\x12\x1e\n" +
	"\n" +
	"executable\x18\x04 \x01(\bR\n" +
	"executable\x12\x14\n" +
	"\x05owner\x18\x06 \x01(\fR\x05ownerJ\x04\b\x05\x10\x06J\x04\b\a\x10\b\"i\n" +
	"\vVoteAccount\x12D\n" +
	"\fvote_account\x18\x01 \x01(\v2!.org.solana.sealevel.v1.AcctStateR\vvoteAccount\x12\x14\n" +
	"\x05stake\x18\x02 \x01(\x04R\x05stake\"\xa0\x01\n" +
	"\tInflation\x12\x18\n" +
	"\ainitial\x18\x01 \x01(\x01R\ainitial\x12\x1a\n" +
	"\bterminal\x18\x02 \x01(\x01R\bterminal\x12\x14\n" +
	"\x05taper\x18\x03 \x01(\x01R\x05taper\x12\x1e\n" +
	"\n" +
	"foundation\x18\x04 \x01(\x01R\n" +
	"foundation\x12'\n" +
	"\x0ffoundation_term\x18\x05 \x01(\x01R\x0efoundationTerm\"\xae\x02\n" +
	"\x0fFeeRateGovernor\x12A\n" +
	"\x1dtarget_lamports_per_signature\x18\x01 \x01(\x04R\x1atargetLamportsPerSignature\x12;\n" +
	"\x1atarget_signatures_per_slot\x18\x02 \x01(\x04R\x17targetSignaturesPerSlot\x12;\n" +
	"\x1amin_lamports_per_signature\x18\x03 \x01(\x04R\x17minLamportsPerSignature\x12;\n" +
	"\x1amax_lamports_per_signature\x18\x04 \x01(\x04R\x17maxLamportsPerSignature\x12!\n" +
	"\fburn_percent\x18\x05 \x01(\rR\vburnPercent\"\xd7\x03\n" +
	"\fEpochContext\x12>\n" +
	"\bfeatures\x18\x01 \x01(\v2\".org.solana.sealevel.v1.FeatureSetR\bfeatures\x12&\n" +
	"\x0fhashes_per_tick\x18\x02 \x01(\x04R\rhashesPerTick\x12$\n" +
	"\x0eticks_per_slot\x18\x03 \x01(\x04R\fticksPerSlot\x12$\n" +
	"\x0eslots_per_year\x18\x04 \x01(\x01R\fslotsPerYear\x12?\n" +
	"\tinflation\x18\x05 \x01(\v2!.org.solana.sealevel.v1.InflationR\tinflation\x122\n" +
	"\x15genesis_creation_time\x18\x06 \x01(\x04R\x13genesisCreationTime\x12N\n" +
	"\x11vote_accounts_t_1\x18\v \x03(\v2#.org.solana.sealevel.v1.VoteAccountR\x0evoteAccountsT1\x12N\n" +
	"\x11vote_accounts_t_2\x18\f \x03(\v2#.org.solana.sealevel.v1.VoteAccountR\x0evoteAccountsT2\"\xa4\x03\n" +
	"\vSlotContext\x12\x12\n" +
	"\x04slot\x18\x01 \x01(\x06R\x04slot\x12!\n" +
	"\fblock_height\x18\x02 \x01(\x06R\vblockHeight\x12\x10\n" +
	"\x03poh\x18\x03 \x01(\fR\x03poh\x12(\n" +
	"\x10parent_bank_hash\x18\x04 \x01(\fR\x0eparentBankHash\x12#\n" +
	"\rparent_lthash\x18\x05 \x01(\fR\fparentLthash\x12\x1b\n" +
	"\tprev_slot\x18\x06 \x01(\x06R\bprevSlot\x12\x19\n" +
	"\bprev_lps\x18\a \x01(\x04R\aprevLps\x12:\n" +
	"\x19prev_epoch_capitalization\x18\b \x01(\x04R\x17prevEpochCapitalization\x12S\n" +
	"\x11fee_rate_governor\x18\t \x01(\v2'.org.solana.sealevel.v1.FeeRateGovernorR\x0ffeeRateGovernor\x124\n" +
	"\x16parent_signature_count\x18\n" +
	" \x01(\x04R\x14parentSignatureCountb\x06proto3"

var (
	file_context_proto_rawDescOnce sync.Once
	file_context_proto_rawDescData []byte
)

func file_context_proto_rawDescGZIP() []byte {
	file_context_proto_rawDescOnce.Do(func() {
		file_context_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_context_proto_rawDesc), len(file_context_proto_rawDesc)))
	})
	return file_context_proto_rawDescData
}

var file_context_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_context_proto_goTypes = []any{
	(*FeatureSet)(nil),      // 0: org.solana.sealevel.v1.FeatureSet
	(*AcctState)(nil),       // 1: org.solana.sealevel.v1.AcctState
	(*VoteAccount)(nil),     // 2: org.solana.sealevel.v1.VoteAccount
	(*Inflation)(nil),       // 3: org.solana.sealevel.v1.Inflation
	(*FeeRateGovernor)(nil), // 4: org.solana.sealevel.v1.FeeRateGovernor
	(*EpochContext)(nil),    // 5: org.solana.sealevel.v1.EpochContext
	(*SlotContext)(nil),     // 6: org.solana.sealevel.v1.SlotContext
}
var file_context_proto_depIdxs = []int32{
	1, // 0: org.solana.sealevel.v1.VoteAccount.vote_account:type_name -> org.solana.sealevel.v1.AcctState
	0, // 1: org.solana.sealevel.v1.EpochContext.features:type_name -> org.solana.sealevel.v1.FeatureSet
	3, // 2: org.solana.sealevel.v1.EpochContext.inflation:type_name -> org.solana.sealevel.v1.Inflation
	2, // 3: org.solana.sealevel.v1.EpochContext.vote_accounts_t_1:type_name -> org.solana.sealevel.v1.VoteAccount
	2, // 4: org.solana.sealevel.v1.EpochContext.vote_accounts_t_2:type_name -> org.solana.sealevel.v1.VoteAccount
	4, // 5: org.solana.sealevel.v1.SlotContext.fee_rate_governor:type_name -> org.solana.sealevel.v1.FeeRateGovernor
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_context_proto_init() }
func file_context_proto_init() {
	if File_context_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_context_proto_rawDesc), len(file_context_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_context_proto_goTypes,
		DependencyIndexes: file_context_proto_depIdxs,
		MessageInfos:      file_context_proto_msgTypes,
	}.Build()
	File_context_proto = out.File
	file_context_proto_goTypes = nil
	file_context_proto_depIdxs = nil
}
