// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: serialize.proto

package serialize

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VmMemRegion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VmAddr        uint64                 `protobuf:"varint,1,opt,name=vm_addr,json=vmAddr,proto3" json:"vm_addr,omitempty"`
	Content       []byte                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	IsWritable    bool                   `protobuf:"varint,3,opt,name=is_writable,json=isWritable,proto3" json:"is_writable,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VmMemRegion) Reset() {
	*x = VmMemRegion{}
	mi := &file_serialize_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VmMemRegion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VmMemRegion) ProtoMessage() {}

func (x *VmMemRegion) ProtoReflect() protoreflect.Message {
	mi := &file_serialize_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VmMemRegion.ProtoReflect.Descriptor instead.
func (*VmMemRegion) Descriptor() ([]byte, []int) {
	return file_serialize_proto_rawDescGZIP(), []int{0}
}

func (x *VmMemRegion) GetVmAddr() uint64 {
	if x != nil {
		return x.VmAddr
	}
	return 0
}

func (x *VmMemRegion) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *VmMemRegion) GetIsWritable() bool {
	if x != nil {
		return x.IsWritable
	}
	return false
}

type InstrSerializeResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        int32                  `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	Regions       []*VmMemRegion         `protobuf:"bytes,2,rep,name=regions,proto3" json:"regions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstrSerializeResult) Reset() {
	*x = InstrSerializeResult{}
	mi := &file_serialize_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstrSerializeResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstrSerializeResult) ProtoMessage() {}

func (x *InstrSerializeResult) ProtoReflect() protoreflect.Message {
	mi := &file_serialize_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstrSerializeResult.ProtoReflect.Descriptor instead.
func (*InstrSerializeResult) Descriptor() ([]byte, []int) {
	return file_serialize_proto_rawDescGZIP(), []int{1}
}

func (x *InstrSerializeResult) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

func (x *InstrSerializeResult) GetRegions() []*VmMemRegion {
	if x != nil {
		return x.Regions
	}
	return nil
}

var File_serialize_proto protoreflect.FileDescriptor

const file_serialize_proto_rawDesc = "" +
	"\n" +
	"\x0fserialize.proto\x12\x16org.solana.sealevel.v1\"a\n" +
	"\vVmMemRegion\x12\x17\n" +
	"\avm_addr\x18\x01 \x01(\x04R\x06vmAddr\x12\x18\n" +
	"\acontent\x18\x02 \x01(\fR\acontent\x12\x1f\n" +
	"\vis_writable\x18\x03 \x01(\bR\n" +
	"isWritable\"m\n" +
	"\x14InstrSerializeResult\x12\x16\n" +
	"\x06result\x18\x01 \x01(\x05R\x06result\x12=\n" +
	"\aregions\x18\x02 \x03(\v2#.org.solana.sealevel.v1.VmMemRegionR\aregionsb\x06proto3"

var (
	file_serialize_proto_rawDescOnce sync.Once
	file_serialize_proto_rawDescData []byte
)

func file_serialize_proto_rawDescGZIP() []byte {
	file_serialize_proto_rawDescOnce.Do(func() {
		file_serialize_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_serialize_proto_rawDesc), len(file_serialize_proto_rawDesc)))
	})
	return file_serialize_proto_rawDescData
}

var file_serialize_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_serialize_proto_goTypes = []any{
	(*VmMemRegion)(nil),          // 0: org.solana.sealevel.v1.VmMemRegion
	(*InstrSerializeResult)(nil), // 1: org.solana.sealevel.v1.InstrSerializeResult
}
var file_serialize_proto_depIdxs = []int32{
	0, // 0: org.solana.sealevel.v1.InstrSerializeResult.regions:type_name -> org.solana.sealevel.v1.VmMemRegion
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_serialize_proto_init() }
func file_serialize_proto_init() {
	if File_serialize_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_serialize_proto_rawDesc), len(file_serialize_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_serialize_proto_goTypes,
		DependencyIndexes: file_serialize_proto_depIdxs,
		MessageInfos:      file_serialize_proto_msgTypes,
	}.Build()
	File_serialize_proto = out.File
	file_serialize_proto_goTypes = nil
	file_serialize_proto_depIdxs = nil
}
