// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: block.proto

package block

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	context "github.com/Overclock-Validator/mithril/pkg/protosol-go/context"
	metadata "github.com/Overclock-Validator/mithril/pkg/protosol-go/metadata"
	txn "github.com/Overclock-Validator/mithril/pkg/protosol-go/txn"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CostTracker struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BlockCost     uint64                 `protobuf:"varint,1,opt,name=block_cost,json=blockCost,proto3" json:"block_cost,omitempty"`
	VoteCost      uint64                 `protobuf:"varint,2,opt,name=vote_cost,json=voteCost,proto3" json:"vote_cost,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CostTracker) Reset() {
	*x = CostTracker{}
	mi := &file_block_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CostTracker) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CostTracker) ProtoMessage() {}

func (x *CostTracker) ProtoReflect() protoreflect.Message {
	mi := &file_block_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CostTracker.ProtoReflect.Descriptor instead.
func (*CostTracker) Descriptor() ([]byte, []int) {
	return file_block_proto_rawDescGZIP(), []int{0}
}

func (x *CostTracker) GetBlockCost() uint64 {
	if x != nil {
		return x.BlockCost
	}
	return 0
}

func (x *CostTracker) GetVoteCost() uint64 {
	if x != nil {
		return x.VoteCost
	}
	return 0
}

type BlockContext struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// All transactions in this microblock (can be 0)
	Txns []*txn.SanitizedTransaction `protobuf:"bytes,1,rep,name=txns,proto3" json:"txns,omitempty"`
	// Input account states
	AcctStates []*context.AcctState `protobuf:"bytes,2,rep,name=acct_states,json=acctStates,proto3" json:"acct_states,omitempty"`
	// The blockhash queue
	BlockhashQueue [][]byte `protobuf:"bytes,3,rep,name=blockhash_queue,json=blockhashQueue,proto3" json:"blockhash_queue,omitempty"`
	// Slot context (contains slot number)
	SlotCtx *context.SlotContext `protobuf:"bytes,4,opt,name=slot_ctx,json=slotCtx,proto3" json:"slot_ctx,omitempty"`
	// Epoch context (contains feature info)
	EpochCtx      *context.EpochContext `protobuf:"bytes,5,opt,name=epoch_ctx,json=epochCtx,proto3" json:"epoch_ctx,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockContext) Reset() {
	*x = BlockContext{}
	mi := &file_block_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockContext) ProtoMessage() {}

func (x *BlockContext) ProtoReflect() protoreflect.Message {
	mi := &file_block_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockContext.ProtoReflect.Descriptor instead.
func (*BlockContext) Descriptor() ([]byte, []int) {
	return file_block_proto_rawDescGZIP(), []int{1}
}

func (x *BlockContext) GetTxns() []*txn.SanitizedTransaction {
	if x != nil {
		return x.Txns
	}
	return nil
}

func (x *BlockContext) GetAcctStates() []*context.AcctState {
	if x != nil {
		return x.AcctStates
	}
	return nil
}

func (x *BlockContext) GetBlockhashQueue() [][]byte {
	if x != nil {
		return x.BlockhashQueue
	}
	return nil
}

func (x *BlockContext) GetSlotCtx() *context.SlotContext {
	if x != nil {
		return x.SlotCtx
	}
	return nil
}

func (x *BlockContext) GetEpochCtx() *context.EpochContext {
	if x != nil {
		return x.EpochCtx
	}
	return nil
}

type LeaderScheduleEffects struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Epoch number for which this leader schedule applies
	LeadersEpoch uint64 `protobuf:"varint,1,opt,name=leaders_epoch,json=leadersEpoch,proto3" json:"leaders_epoch,omitempty"`
	// First slot number covered by this leader schedule
	LeadersSlot0 uint64 `protobuf:"varint,2,opt,name=leaders_slot0,json=leadersSlot0,proto3" json:"leaders_slot0,omitempty"`
	// Total number of slots covered by this leader schedule
	LeadersSlotCnt uint64 `protobuf:"varint,3,opt,name=leaders_slot_cnt,json=leadersSlotCnt,proto3" json:"leaders_slot_cnt,omitempty"`
	// Number of unique validator public keys in the leader schedule
	LeaderPubCnt uint64 `protobuf:"varint,4,opt,name=leader_pub_cnt,json=leaderPubCnt,proto3" json:"leader_pub_cnt,omitempty"`
	// Number of entries in the leader schedule (slots with assigned leaders)
	LeadersSchedCnt uint64 `protobuf:"varint,5,opt,name=leaders_sched_cnt,json=leadersSchedCnt,proto3" json:"leaders_sched_cnt,omitempty"`
	// Hash of the leader schedule
	LeaderScheduleHash []byte `protobuf:"bytes,6,opt,name=leader_schedule_hash,json=leaderScheduleHash,proto3" json:"leader_schedule_hash,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *LeaderScheduleEffects) Reset() {
	*x = LeaderScheduleEffects{}
	mi := &file_block_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaderScheduleEffects) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaderScheduleEffects) ProtoMessage() {}

func (x *LeaderScheduleEffects) ProtoReflect() protoreflect.Message {
	mi := &file_block_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaderScheduleEffects.ProtoReflect.Descriptor instead.
func (*LeaderScheduleEffects) Descriptor() ([]byte, []int) {
	return file_block_proto_rawDescGZIP(), []int{2}
}

func (x *LeaderScheduleEffects) GetLeadersEpoch() uint64 {
	if x != nil {
		return x.LeadersEpoch
	}
	return 0
}

func (x *LeaderScheduleEffects) GetLeadersSlot0() uint64 {
	if x != nil {
		return x.LeadersSlot0
	}
	return 0
}

func (x *LeaderScheduleEffects) GetLeadersSlotCnt() uint64 {
	if x != nil {
		return x.LeadersSlotCnt
	}
	return 0
}

func (x *LeaderScheduleEffects) GetLeaderPubCnt() uint64 {
	if x != nil {
		return x.LeaderPubCnt
	}
	return 0
}

func (x *LeaderScheduleEffects) GetLeadersSchedCnt() uint64 {
	if x != nil {
		return x.LeadersSchedCnt
	}
	return 0
}

func (x *LeaderScheduleEffects) GetLeaderScheduleHash() []byte {
	if x != nil {
		return x.LeaderScheduleHash
	}
	return nil
}

type BlockEffects struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// If block execution failed
	HasError bool `protobuf:"varint,1,opt,name=has_error,json=hasError,proto3" json:"has_error,omitempty"`
	// Slot capitalization
	SlotCapitalization uint64 `protobuf:"varint,2,opt,name=slot_capitalization,json=slotCapitalization,proto3" json:"slot_capitalization,omitempty"`
	// Bank hash
	BankHash []byte `protobuf:"bytes,3,opt,name=bank_hash,json=bankHash,proto3" json:"bank_hash,omitempty"`
	// The cost tracker
	CostTracker *CostTracker `protobuf:"bytes,4,opt,name=cost_tracker,json=costTracker,proto3" json:"cost_tracker,omitempty"`
	// Leader schedule
	LeaderSchedule *LeaderScheduleEffects `protobuf:"bytes,5,opt,name=leader_schedule,json=leaderSchedule,proto3" json:"leader_schedule,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *BlockEffects) Reset() {
	*x = BlockEffects{}
	mi := &file_block_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockEffects) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockEffects) ProtoMessage() {}

func (x *BlockEffects) ProtoReflect() protoreflect.Message {
	mi := &file_block_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockEffects.ProtoReflect.Descriptor instead.
func (*BlockEffects) Descriptor() ([]byte, []int) {
	return file_block_proto_rawDescGZIP(), []int{3}
}

func (x *BlockEffects) GetHasError() bool {
	if x != nil {
		return x.HasError
	}
	return false
}

func (x *BlockEffects) GetSlotCapitalization() uint64 {
	if x != nil {
		return x.SlotCapitalization
	}
	return 0
}

func (x *BlockEffects) GetBankHash() []byte {
	if x != nil {
		return x.BankHash
	}
	return nil
}

func (x *BlockEffects) GetCostTracker() *CostTracker {
	if x != nil {
		return x.CostTracker
	}
	return nil
}

func (x *BlockEffects) GetLeaderSchedule() *LeaderScheduleEffects {
	if x != nil {
		return x.LeaderSchedule
	}
	return nil
}

type BlockFixture struct {
	state    protoimpl.MessageState    `protogen:"open.v1"`
	Metadata *metadata.FixtureMetadata `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	// The block input
	Input *BlockContext `protobuf:"bytes,2,opt,name=input,proto3" json:"input,omitempty"`
	// The output
	Output        *BlockEffects `protobuf:"bytes,3,opt,name=output,proto3" json:"output,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockFixture) Reset() {
	*x = BlockFixture{}
	mi := &file_block_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockFixture) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockFixture) ProtoMessage() {}

func (x *BlockFixture) ProtoReflect() protoreflect.Message {
	mi := &file_block_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockFixture.ProtoReflect.Descriptor instead.
func (*BlockFixture) Descriptor() ([]byte, []int) {
	return file_block_proto_rawDescGZIP(), []int{4}
}

func (x *BlockFixture) GetMetadata() *metadata.FixtureMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *BlockFixture) GetInput() *BlockContext {
	if x != nil {
		return x.Input
	}
	return nil
}

func (x *BlockFixture) GetOutput() *BlockEffects {
	if x != nil {
		return x.Output
	}
	return nil
}

var File_block_proto protoreflect.FileDescriptor

const file_block_proto_rawDesc = "" +
	"\n" +
	"\vblock.proto\x12\x16org.solana.sealevel.v1\x1a\rcontext.proto\x1a\ttxn.proto\x1a\x0emetadata.proto\"I\n" +
	"\vCostTracker\x12\x1d\n" +
	"\n" +
	"block_cost\x18\x01 \x01(\x04R\tblockCost\x12\x1b\n" +
	"\tvote_cost\x18\x02 \x01(\x04R\bvoteCost\"\xc0\x02\n" +
	"\fBlockContext\x12@\n" +
	"\x04txns\x18\x01 \x03(\v2,.org.solana.sealevel.v1.SanitizedTransactionR\x04txns\x12B\n" +
	"\vacct_states\x18\x02 \x03(\v2!.org.solana.sealevel.v1.AcctStateR\n" +
	"acctStates\x12'\n" +
	"\x0fblockhash_queue\x18\x03 \x03(\fR\x0eblockhashQueue\x12>\n" +
	"\bslot_ctx\x18\x04 \x01(\v2#.org.solana.sealevel.v1.SlotContextR\aslotCtx\x12A\n" +
	"\tepoch_ctx\x18\x05 \x01(\v2$.org.solana.sealevel.v1.EpochContextR\bepochCtx\"\x8f\x02\n" +
	"\x15LeaderScheduleEffects\x12#\n" +
	"\rleaders_epoch\x18\x01 \x01(\x04R\fleadersEpoch\x12#\n" +
	"\rleaders_slot0\x18\x02 \x01(\x04R\fleadersSlot0\x12(\n" +
	"\x10leaders_slot_cnt\x18\x03 \x01(\x04R\x0eleadersSlotCnt\x12$\n" +
	"\x0eleader_pub_cnt\x18\x04 \x01(\x04R\fleaderPubCnt\x12*\n" +
	"\x11leaders_sched_cnt\x18\x05 \x01(\x04R\x0fleadersSchedCnt\x120\n" +
	"\x14leader_schedule_hash\x18\x06 \x01(\fR\x12leaderScheduleHash\"\x99\x02\n" +
	"\fBlockEffects\x12\x1b\n" +
	"\thas_error\x18\x01 \x01(\bR\bhasError\x12/\n" +
	"\x13slot_capitalization\x18\x02 \x01(\x04R\x12slotCapitalization\x12\x1b\n" +
	"\tbank_hash\x18\x03 \x01(\fR\bbankHash\x12F\n" +
	"\fcost_tracker\x18\x04 \x01(\v2#.org.solana.sealevel.v1.CostTrackerR\vcostTracker\x12V\n" +
	"\x0fleader_schedule\x18\x05 \x01(\v2-.org.solana.sealevel.v1.LeaderScheduleEffectsR\x0eleaderSchedule\"\xcd\x01\n" +
	"\fBlockFixture\x12C\n" +
	"\bmetadata\x18\x01 \x01(\v2'.org.solana.sealevel.v1.FixtureMetadataR\bmetadata\x12:\n" +
	"\x05input\x18\x02 \x01(\v2$.org.solana.sealevel.v1.BlockContextR\x05input\x12<\n" +
	"\x06output\x18\x03 \x01(\v2$.org.solana.sealevel.v1.BlockEffectsR\x06outputb\x06proto3"

var (
	file_block_proto_rawDescOnce sync.Once
	file_block_proto_rawDescData []byte
)

func file_block_proto_rawDescGZIP() []byte {
	file_block_proto_rawDescOnce.Do(func() {
		file_block_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_block_proto_rawDesc), len(file_block_proto_rawDesc)))
	})
	return file_block_proto_rawDescData
}

var file_block_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_block_proto_goTypes = []any{
	(*CostTracker)(nil),              // 0: org.solana.sealevel.v1.CostTracker
	(*BlockContext)(nil),             // 1: org.solana.sealevel.v1.BlockContext
	(*LeaderScheduleEffects)(nil),    // 2: org.solana.sealevel.v1.LeaderScheduleEffects
	(*BlockEffects)(nil),             // 3: org.solana.sealevel.v1.BlockEffects
	(*BlockFixture)(nil),             // 4: org.solana.sealevel.v1.BlockFixture
	(*txn.SanitizedTransaction)(nil), // 5: org.solana.sealevel.v1.SanitizedTransaction
	(*context.AcctState)(nil),        // 6: org.solana.sealevel.v1.AcctState
	(*context.SlotContext)(nil),      // 7: org.solana.sealevel.v1.SlotContext
	(*context.EpochContext)(nil),     // 8: org.solana.sealevel.v1.EpochContext
	(*metadata.FixtureMetadata)(nil), // 9: org.solana.sealevel.v1.FixtureMetadata
}
var file_block_proto_depIdxs = []int32{
	5, // 0: org.solana.sealevel.v1.BlockContext.txns:type_name -> org.solana.sealevel.v1.SanitizedTransaction
	6, // 1: org.solana.sealevel.v1.BlockContext.acct_states:type_name -> org.solana.sealevel.v1.AcctState
	7, // 2: org.solana.sealevel.v1.BlockContext.slot_ctx:type_name -> org.solana.sealevel.v1.SlotContext
	8, // 3: org.solana.sealevel.v1.BlockContext.epoch_ctx:type_name -> org.solana.sealevel.v1.EpochContext
	0, // 4: org.solana.sealevel.v1.BlockEffects.cost_tracker:type_name -> org.solana.sealevel.v1.CostTracker
	2, // 5: org.solana.sealevel.v1.BlockEffects.leader_schedule:type_name -> org.solana.sealevel.v1.LeaderScheduleEffects
	9, // 6: org.solana.sealevel.v1.BlockFixture.metadata:type_name -> org.solana.sealevel.v1.FixtureMetadata
	1, // 7: org.solana.sealevel.v1.BlockFixture.input:type_name -> org.solana.sealevel.v1.BlockContext
	3, // 8: org.solana.sealevel.v1.BlockFixture.output:type_name -> org.solana.sealevel.v1.BlockEffects
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	9, // [9:9] is the sub-list for extension type_name
	9, // [9:9] is the sub-list for extension extendee
	0, // [0:9] is the sub-list for field type_name
}

func init() { file_block_proto_init() }
func file_block_proto_init() {
	if File_block_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_block_proto_rawDesc), len(file_block_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_block_proto_goTypes,
		DependencyIndexes: file_block_proto_depIdxs,
		MessageInfos:      file_block_proto_msgTypes,
	}.Build()
	File_block_proto = out.File
	file_block_proto_goTypes = nil
	file_block_proto_depIdxs = nil
}
