package txverify

import (
	"encoding/hex"
	"testing"

	"github.com/gagliardetto/solana-go"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

// Generated by the Rust Solana SDK with signer seed [1; 32]. Retained here as
// a cross-language SIMD-0385 boundary vector (Apache-2.0 upstream).
const rustV1FeeHeapTransaction = "8101000113000000070707070707070707070707070707070707070707070707070707070707070701028a88e3dd7409" +
	"f195fd52db2d3cba5d72ca6709bf1d94121bf3748801b40f6f5c10101010101010101010101010101010101010101010" +
	"10101010101010101010010000000000000000800000010100000070083fb1bf5a9e2c90c6903b7328529cdf59e04e2f" +
	"cf29c718bea8c76fd325f4b67e18feb1f95f9aab171140b81b8c8238c9ffea33d4133bae92af68c6453800"

func TestV1RustVectorUsesMessagePrefixAndSignatureTail(t *testing.T) {
	wire, err := hex.DecodeString(rustV1FeeHeapTransaction)
	require.NoError(t, err)
	tx, err := solana.TransactionFromBytes(wire)
	require.NoError(t, err)
	require.Equal(t, solana.MessageVersionV1, tx.Message.GetVersion())

	message, err := MessageBytes(tx)
	require.NoError(t, err)
	require.NotEmpty(t, message)
	assert.Equal(t, byte(0x81), message[0])
	assert.Equal(t, wire[:len(wire)-64], message)
	assert.Equal(t, tx.Signatures[0][:], wire[len(wire)-64:])
	assert.NoError(t, SanitizeTransaction(tx))
	assert.NoError(t, VerifyTransaction(tx))
}

func TestSanitizeTransactionEnforcesV1WireLimit(t *testing.T) {
	msg := solana.Message{
		Header: solana.MessageHeader{
			NumRequiredSignatures:       1,
			NumReadonlyUnsignedAccounts: 1,
		},
		AccountKeys:     []solana.PublicKey{{1}, {2}},
		RecentBlockhash: solana.Hash{3},
		Instructions: []solana.CompiledInstruction{{
			ProgramIDIndex: 1,
			Accounts:       []uint16{0},
		}},
	}
	_, err := msg.SetVersion(solana.MessageVersionV1)
	require.NoError(t, err)
	tx := &solana.Transaction{Message: msg, Signatures: []solana.Signature{{}}}

	baseSize, err := TransactionWireSize(tx)
	require.NoError(t, err)
	tx.Message.Instructions[0].Data = make([]byte, solana.MaxTransactionSizeV1-baseSize)
	size, err := TransactionWireSize(tx)
	require.NoError(t, err)
	assert.Equal(t, solana.MaxTransactionSizeV1, size)
	assert.NoError(t, SanitizeTransaction(tx))

	tx.Message.Instructions[0].Data = append(tx.Message.Instructions[0].Data, 0)
	size, err = TransactionWireSize(tx)
	require.NoError(t, err)
	assert.Equal(t, solana.MaxTransactionSizeV1+1, size)
	assert.Error(t, SanitizeTransaction(tx))
}

func TestTransactionWireSizeMatchesCanonicalEncoding(t *testing.T) {
	wire, err := hex.DecodeString(rustV1FeeHeapTransaction)
	require.NoError(t, err)
	tx, err := solana.TransactionFromBytes(wire)
	require.NoError(t, err)

	size, err := TransactionWireSize(tx)
	require.NoError(t, err)
	assert.Equal(t, len(wire), size)

	for _, version := range []solana.MessageVersion{solana.MessageVersionLegacy, solana.MessageVersionV0} {
		msg := solana.Message{
			Header:          solana.MessageHeader{NumRequiredSignatures: 1, NumReadonlyUnsignedAccounts: 1},
			AccountKeys:     []solana.PublicKey{{1}, {2}},
			RecentBlockhash: solana.Hash{3},
			Instructions: []solana.CompiledInstruction{{
				ProgramIDIndex: 1,
				Accounts:       []uint16{0},
				Data:           []byte{4, 5, 6},
			}},
		}
		_, err := msg.SetVersion(version)
		require.NoError(t, err)
		candidate := &solana.Transaction{Message: msg, Signatures: []solana.Signature{{}}}
		encoded, err := candidate.MarshalBinary()
		require.NoError(t, err)
		size, err := TransactionWireSize(candidate)
		require.NoError(t, err)
		assert.Equal(t, len(encoded), size, "version %d", version)
	}
}

func TestTransactionWireSizeResolvedV0UsesStaticKeys(t *testing.T) {
	tableKey := solana.PublicKey{9}
	dynamicKey := solana.PublicKey{8}
	msg := solana.Message{
		Header:          solana.MessageHeader{NumRequiredSignatures: 1, NumReadonlyUnsignedAccounts: 1},
		AccountKeys:     []solana.PublicKey{{1}, {2}},
		RecentBlockhash: solana.Hash{3},
		Instructions: []solana.CompiledInstruction{{
			ProgramIDIndex: 1,
			Accounts:       []uint16{0, 2},
		}},
	}
	msg.SetAddressTableLookups([]solana.MessageAddressTableLookup{{
		AccountKey:      tableKey,
		WritableIndexes: []uint8{0},
	}})
	tx := &solana.Transaction{Message: msg, Signatures: []solana.Signature{{}}}
	wire, err := tx.MarshalBinary()
	require.NoError(t, err)

	require.NoError(t, tx.Message.SetAddressTables(map[solana.PublicKey]solana.PublicKeySlice{
		tableKey: {dynamicKey},
	}))
	require.NoError(t, tx.Message.ResolveLookups())
	require.True(t, tx.Message.IsResolved())

	size, err := TransactionWireSize(tx)
	require.NoError(t, err)
	assert.Equal(t, len(wire), size)
	assert.NoError(t, SanitizeTransaction(tx))
}
